// GENERATED by scripts/gen-motors.mjs — do not edit by hand.
//
// The bundled offline motor database: authentic RASP thrust curves from ThrustCurve.org,
// inlined verbatim so the simulator resolves motors client-side with no network. Thrust-vs-
// time is factual certification / test-stand data; each entry records its ThrustCurve.org
// simfile id, info URL, and license for auditability. Regenerate with:
//   node scripts/gen-motors.mjs

export interface CatalogSource {
  file: string;
  motorId: string | null;
  simfileId: string | null;
  license: string | null;
  infoUrl: string | null;
}

export interface CatalogEntry {
  /** Raw RASP .eng text, parsed at load by lib/motors/eng.ts. */
  eng: string;
  source: CatalogSource;
}

export const MOTOR_CATALOG: CatalogEntry[] = [
  {
    "eng": ";\n;AMW L1100 RASP.ENG file made from NAR published data\n;File produced April 19, 2004\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nL1100RR 75 728 100 1.346 2.5881 Animal_Motor_Works \n0.013 681.489\n0.029 1116.88\n0.041 1196.3\n0.079 1210.38\n0.147 1203.34\n0.257 1218.42\n0.366 1225.45\n0.567 1254.61\n0.824 1282.76\n1.059 1311.91\n1.267 1340.23\n1.459 1311.91\n1.622 1297.84\n1.713 1290.8\n1.785 1268.68\n1.83 1218.42\n1.886 1080.69\n1.969 819.214\n2.048 558.24\n2.108 376.985\n2.156 246.498\n2.205 144.963\n2.269 72.501\n2.35 0",
    "source": {
      "file": "AMW_L1100.eng",
      "motorId": "5f4294d2000231000000018b",
      "simfileId": "5f4294d20002e90000000482",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000482/"
    }
  },
  {
    "eng": ";Aerotech D21 RASP.ENG file made from NAR published data\n;File produced July 4, 2000\n;Submitted to ThrustCurve.org by Chris Kobel (3/29/07)\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD21T 18 70 4-7 0.0096 0.025 AT \n   0.01   1.367\n   0.021 19.367\n   0.029 32.12\n   0.037 31.667\n   0.051 30.528\n   0.094 30.074\n   0.115 31.213\n   0.133 30.074\n   0.177 30.76\n   0.189 29.842\n   0.203 30.528\n   0.226 29.842\n   0.275 28.935\n   0.296 29.389\n   0.331 28.027\n   0.421 25.971\n   0.478 24.146\n   0.579 20.728\n   0.659 17.774\n   0.739 14.356\n   0.799  9.569\n   0.852  4.557\n   0.899  1.139\n   0.94   0\n",
    "source": {
      "file": "AeroTech_D21T.eng",
      "motorId": "5f4294d20002310000000023",
      "simfileId": "5f4294d20002e9000000027d",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000027d/"
    }
  },
  {
    "eng": "; Aerotech E30 RASP.ENG file made from NAR published data\n; File produced Sept 30, 2010\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nE30 24 70 4-7 .0178 .047 A\n0.006 49.3000\n0.030 45.7010\n0.038 47.1810\n0.050 45.1800\n0.062 43.7010\n0.112 43.4020\n0.138 42.8170\n0.206 42.0730\n0.238 43.3680\n0.282 41.5750\n0.324 41.0860\n0.342 41.7330\n0.362 40.1680\n0.436 38.1580\n0.524 36.3980\n0.650 32.9720\n0.712 31.0500\n0.836 25.0770\n0.874 22.4750\n0.888 21.5080\n0.900 20.0080\n0.912 17.1760\n0.924 13.3000\n0.942 6.6500\n0.962 2.7550\n0.974 1.6370\n0.988 0.7810\n1.000 0.4290\n1.010 0.1410\n1.020 0.0000\n",
    "source": {
      "file": "AeroTech_E30T.eng",
      "motorId": "5f4294d20002310000000034",
      "simfileId": "62431a34ee302a00044520da",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/62431a34ee302a00044520da/"
    }
  },
  {
    "eng": ";\n;Aerotech F50 RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case F50T motors.\nF50T 29 98 4-6-9 0.0336 0.0898 AeroTech\n0.013 73.762\n0.0326 70.383\n0.267 69.82\n0.518 67.005\n0.792 56.87\n0.906 50.676\n1 44.482\n1.036 39.978\n1.107 23.649\n1.199 6.194\n1.316 1.126\n1.43 0\n",
    "source": {
      "file": "AeroTech_F50T.eng",
      "motorId": "5f4294d20002310000000049",
      "simfileId": "5f4294d20002e9000000045b",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000045b/"
    }
  },
  {
    "eng": "F67W 29 83 4-6-9 0.03 0.08 AT\n   0.002 66.662\n   0.008 71.441\n   0.016 74.505\n   0.039 77.936\n   0.068 80.632\n   0.099 82.592\n   0.148 84.43\n   0.201 85.533\n   0.257 86.146\n   0.298 86.023\n   0.399 84.185\n   0.483 82.96\n   0.499 82.347\n   0.568 80.019\n   0.601 78.794\n   0.625 77.936\n   0.654 78.058\n   0.672 75.853\n   0.687 71.073\n   0.7 67.52\n   0.714 62.005\n   0.731 53.06\n   0.748 44.482\n   0.764 35.659\n   0.778 26.836\n   0.789 20.954\n   0.797 18.013\n   0.812 12.499\n   0.832 7.107\n   0.849 3.676\n   0.87 1.225\n   0.898 0.368\n   0.92 0.0\n",
    "source": {
      "file": "AeroTech_F67W.eng",
      "motorId": "5f4294d2000231000000045a",
      "simfileId": "5f4294d20002e9000000088a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000088a/"
    }
  },
  {
    "eng": ";\n;Aerotech G40W RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case G40W motors.\nG40W 29 124 4-7-10 0.0538 0.123 AeroTech\n0.024 74.325\n0.057 67.005\n0.252 65.879\n0.5 63.063\n0.765 60.248\n1 54.054\n1.25 47.298\n1.502 36.599\n1.751 25.338\n1.999 12.951\n2.121 3.941\n2.3 0\n",
    "source": {
      "file": "AeroTech_G40W.eng",
      "motorId": "5f4294d20002310000000059",
      "simfileId": "5f4294d20002e90000000463",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000463/"
    }
  },
  {
    "eng": ";G80 New Blue Thunder\nG80NBT 29 123.825 4-7-10 0.069 0.129 AT \n0.013 89.054\n0.018 101.584\n0.029 105.388\n0.047 102.927\n0.104 100.018\n0.19 102.255\n0.268 104.94\n0.306 104.269\n0.352 105.835\n0.41 104.94\n0.432 106.73\n0.512 105.612\n0.563 106.954\n0.591 104.493\n0.62 106.283\n0.715 103.15\n0.76 103.374\n0.806 101.36\n0.848 102.032\n1.2 88.383\n1.243 77.866\n1.269 57.952\n1.302 44.079\n1.329 34.011\n1.367 26.403\n1.398 22.823\n1.433 20.585\n1.48 21.704\n1.508 20.809\n1.584 13.201\n1.604 11.635\n1.652 11.188\n1.683 5.37\n1.701 0\n;\n",
    "source": {
      "file": "AeroTech_G80T.eng",
      "motorId": "5f4294d20002310000000068",
      "simfileId": "5f4294d20002e900000007dd",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007dd/"
    }
  },
  {
    "eng": "; H100W DMS\r\nH100W 38 157.5 14 0.121 0.261 AT\r\n   0.004 46.916\r\n   0.031 66.29\r\n   0.047 97.334\r\n   0.096 109.005\r\n   0.193 116.474\r\n   0.302 124.877\r\n   0.391 123.01\r\n   0.498 127.911\r\n   0.604 128.845\r\n   0.696 130.245\r\n   0.798 128.612\r\n   0.902 128.845\r\n   0.998 127.445\r\n   1.098 126.511\r\n   1.2 116.941\r\n   1.3 114.607\r\n   1.4 110.172\r\n   1.5 98.268\r\n   1.6 90.798\r\n   1.7 80.061\r\n   1.802 68.624\r\n   1.9 65.356\r\n   2.0 56.953\r\n   2.1 49.484\r\n   2.202 25.209\r\n   2.298 5.135\r\n   2.398 0.0",
    "source": {
      "file": "AeroTech_H100W.eng",
      "motorId": "5f4294d20002310000000440",
      "simfileId": "5f4294d20002e90000000854",
      "license": "free",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000854/"
    }
  },
  {
    "eng": "; AeroTech H128W\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH128W 29 194 14 0.09408 0.2016 AT\n   0.024 102.423\n   0.074 175.203\n   0.125 181.379\n   0.176 179.281\n   0.226 181.423\n   0.277 186.074\n   0.328 190.483\n   0.378 189.509\n   0.429 186.162\n   0.480 184.114\n   0.530 180.300\n   0.581 174.144\n   0.632 172.019\n   0.683 169.360\n   0.734 166.017\n   0.784 161.882\n   0.835 157.331\n   0.886 153.073\n   0.936 151.985\n   0.988 139.902\n   1.039 87.865\n   1.089 40.857\n   1.140 14.328\n   1.191 4.330\n   1.242 1.550\n   1.293 0.000\n",
    "source": {
      "file": "AeroTech_H128W.eng",
      "motorId": "5f4294d20002310000000083",
      "simfileId": "5f4294d20002e9000000000d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000d/"
    }
  },
  {
    "eng": "; AeroTech H148R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH148R 38 152 0 0.14784 0.30912 AT\n   0.027 77.232\n   0.088 174.296\n   0.148 185.046\n   0.208 190.458\n   0.268 192.497\n   0.327 191.996\n   0.388 188.790\n   0.448 187.548\n   0.509 182.697\n   0.570 178.151\n   0.630 172.906\n   0.690 169.607\n   0.750 164.510\n   0.810 158.375\n   0.870 153.019\n   0.930 146.810\n   0.991 139.443\n   1.053 132.001\n   1.112 123.271\n   1.173 112.559\n   1.233 104.737\n   1.292 97.657\n   1.353 94.932\n   1.413 60.644\n   1.474 13.007\n   1.535 0.000\n",
    "source": {
      "file": "AeroTech_H148R.eng",
      "motorId": "5f4294d20002310000000087",
      "simfileId": "5f4294d20002e9000000000f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000f/"
    }
  },
  {
    "eng": "; AeroTech H180W\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH180W 29 238 6 0.12096 0.2464 AT\n   0.024 149.374\n   0.075 222.273\n   0.127 222.339\n   0.178 227.835\n   0.229 234.963\n   0.281 238.162\n   0.333 240.252\n   0.384 243.126\n   0.435 240.757\n   0.487 240.724\n   0.539 236.311\n   0.590 236.799\n   0.642 234.897\n   0.694 232.763\n   0.745 229.198\n   0.796 228.816\n   0.848 231.906\n   0.899 225.853\n   0.950 188.285\n   1.002 134.679\n   1.054 78.940\n   1.105 34.557\n   1.156 15.482\n   1.208 7.279\n   1.260 3.585\n   1.313 0.000",
    "source": {
      "file": "AeroTech_H180W.eng",
      "motorId": "5f4294d2000231000000008b",
      "simfileId": "5f4294d20002e90000000013",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000013/"
    }
  },
  {
    "eng": ";\n; 38-240\n;  Greg Gardner - 09/15/06\nH669N  38 152  0  0.096  0.252  AT\n0.003  141\n0.006  523\n0.009  934\n0.012  1178\n0.016  926\n0.019  684\n0.022  487\n0.025  415\n0.028  622\n0.031  801\n0.0325  906\n0.034  866\n0.037  755\n0.04   737\n0.043  666\n0.047  737\n0.0485  802\n0.05   755\n0.053  791\n0.056  765\n0.059  755\n0.062  747\n0.069  737\n0.075  761\n0.082  755\n0.088  729\n0.093  741\n0.1    751\n0.2    703\n0.25   640\n0.3    586\n0.306  584\n0.309  576\n0.312  506\n0.318  292\n0.325  93\n0.329  0\n;\n",
    "source": {
      "file": "AeroTech_H669N.eng",
      "motorId": "5f4294d2000231000000009b",
      "simfileId": "5f4294d20002e9000000026a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000026a/"
    }
  },
  {
    "eng": "; Aerotech I115W from TRA Cert Data\nI115W 54 156 6-10-14-P 0.229 0.58 AT\n   0.034 12.095\n   0.177 105.225\n   0.206 113.087\n   1.017 163.281\n   1.166 161.466\n   1.257 162.676\n   1.343 166.909\n   1.417 160.862\n   1.514 162.676\n   1.617 163.885\n   1.686 160.257\n   1.977 142.719\n   2.497 106.435\n   2.68 91.316\n   2.994 72.569\n   3.103 67.126\n   3.189 65.917\n   3.24 59.265\n   3.291 42.937\n   3.331 30.237\n   3.377 20.561\n   3.429 12.7\n   3.491 7.257\n   3.514 0.0\n",
    "source": {
      "file": "AeroTech_I115W.eng",
      "motorId": "5f4294d200023100000001e7",
      "simfileId": "5f4294d20002e90000000423",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000423/"
    }
  },
  {
    "eng": "; AeroTech I161W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI161W 38 191 0 0.189952 0.370048 AT\n   0.043 178.900\n   0.131 206.770\n   0.221 206.101\n   0.310 205.175\n   0.400 206.924\n   0.490 210.603\n   0.579 210.475\n   0.669 211.555\n   0.758 212.379\n   0.848 212.096\n   0.938 209.060\n   1.027 202.345\n   1.116 192.439\n   1.204 179.499\n   1.294 162.159\n   1.383 148.446\n   1.473 135.222\n   1.563 120.095\n   1.652 104.041\n   1.742 87.962\n   1.831 74.789\n   1.921 54.362\n   2.010 23.386\n   2.100 7.332\n   2.190 5.171\n   2.279 0.000\n",
    "source": {
      "file": "AeroTech_I161W.eng",
      "motorId": "5f4294d200023100000000b1",
      "simfileId": "5f4294d20002e9000000002d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000002d/"
    }
  },
  {
    "eng": "; AeroTech I200W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI200W 29 333 0 0.181888 0.357504 AT\n   0.033 303.951\n   0.103 273.452\n   0.174 276.061\n   0.245 271.625\n   0.316 268.233\n   0.386 258.449\n   0.457 252.480\n   0.528 246.642\n   0.599 242.304\n   0.670 237.737\n   0.741 234.769\n   0.811 233.171\n   0.882 230.660\n   0.953 224.985\n   1.024 221.658\n   1.095 214.548\n   1.166 177.365\n   1.236 154.208\n   1.307 119.146\n   1.378 91.586\n   1.449 65.330\n   1.520 32.877\n   1.591 28.702\n   1.661 22.211\n   1.732 15.558\n   1.803 0.000",
    "source": {
      "file": "AeroTech_I200W.eng",
      "motorId": "5f4294d200023100000000b5",
      "simfileId": "5f4294d20002e90000000033",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000033/"
    }
  },
  {
    "eng": "; AeroTech I211W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI211W 38 240 0 0.247296 0.466368 AT\n   0.044 257.326\n   0.134 295.533\n   0.226 296.087\n   0.318 298.204\n   0.408 295.082\n   0.499 287.669\n   0.591 282.578\n   0.682 272.875\n   0.773 266.997\n   0.864 257.602\n   0.955 250.495\n   1.047 238.574\n   1.138 228.571\n   1.228 215.135\n   1.320 198.047\n   1.411 180.631\n   1.502 161.261\n   1.593 146.708\n   1.684 134.484\n   1.776 101.241\n   1.867 52.688\n   1.957 35.461\n   2.049 24.321\n   2.141 11.165\n   2.232 4.587\n   2.324 0.000\n",
    "source": {
      "file": "AeroTech_I211W.eng",
      "motorId": "5f4294d200023100000000b9",
      "simfileId": "5f4294d20002e90000000035",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000035/"
    }
  },
  {
    "eng": "; AeroTech I284W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI284W 38 297 0 0.310016 0.555072 AT\n   0.041 422.031\n   0.125 448.597\n   0.210 459.029\n   0.295 451.940\n   0.379 439.556\n   0.465 427.370\n   0.549 407.558\n   0.633 399.734\n   0.719 380.049\n   0.803 368.042\n   0.887 352.020\n   0.973 342.102\n   1.057 325.767\n   1.142 306.936\n   1.227 292.029\n   1.311 267.283\n   1.396 251.784\n   1.481 227.534\n   1.566 210.504\n   1.650 168.299\n   1.735 110.789\n   1.820 71.036\n   1.904 32.505\n   1.990 17.537\n   2.075 7.317\n   2.160 0.000",
    "source": {
      "file": "AeroTech_I284W.eng",
      "motorId": "5f4294d200023100000000c5",
      "simfileId": "5f4294d20002e9000000003b",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000003b/"
    }
  },
  {
    "eng": "; AeroTech J350W\r\n; converted from TMT test stand data 1998 (www.tripoli.org)\r\n; provided by ThrustCurve.org (www.thrustcurve.org)\r\nJ350W 38 337 0 0.375872 0.650944 AT\r\n   0.038 706.781\r\n   0.115 669.055\r\n   0.192 602.539\r\n   0.270 565.084\r\n   0.348 539.143\r\n   0.425 514.910\r\n   0.503 483.098\r\n   0.581 449.128\r\n   0.658 437.256\r\n   0.736 424.199\r\n   0.815 414.461\r\n   0.892 402.956\r\n   0.970 393.604\r\n   1.048 377.837\r\n   1.125 359.785\r\n   1.203 341.916\r\n   1.281 324.721\r\n   1.358 305.935\r\n   1.436 264.279\r\n   1.515 175.471\r\n   1.592 110.912\r\n   1.670 77.100\r\n   1.748 55.472\r\n   1.825 39.990\r\n   1.903 26.276\r\n   1.981 0.000\r\n;",
    "source": {
      "file": "AeroTech_J350W.eng",
      "motorId": "5f4294d2000231000000010e",
      "simfileId": "5f4294d20002e900000002a7",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000002a7/"
    }
  },
  {
    "eng": "; AeroTech J420R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ420R 38 337 0 0.37632 0.6496 AT\n   0.031 61.083\n   0.095 563.470\n   0.160 525.283\n   0.224 521.242\n   0.288 527.371\n   0.352 537.088\n   0.418 535.138\n   0.481 534.623\n   0.545 530.245\n   0.610 526.447\n   0.674 517.203\n   0.738 510.279\n   0.802 500.887\n   0.868 479.450\n   0.931 460.675\n   0.995 438.594\n   1.060 409.647\n   1.124 383.454\n   1.188 361.024\n   1.252 339.741\n   1.318 319.194\n   1.381 296.714\n   1.445 195.191\n   1.510 61.984\n   1.575 7.220\n   1.640 0.000\n",
    "source": {
      "file": "AeroTech_J420R.eng",
      "motorId": "5f4294d2000231000000011c",
      "simfileId": "5f4294d20002e90000000057",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000057/"
    }
  },
  {
    "eng": ";Delays are speculation.\r\n;Taken from Aerotech curves, not cert docs.\r\n;Jim Yehle 15 Nov 07\r\nJ500G 38 335.407 0-6-10-14 0.3626 0.654 Aerotech \r\n0.0134378 40.2458\r\n0.0335946 724.425\r\n0.0403135 781.616\r\n0.0604703 787.971\r\n0.0895857 711.716\r\n0.134378 686.297\r\n0.394177 637.578\r\n0.575588 588.86\r\n0.606943 622.751\r\n0.633819 620.633\r\n1.20045 360.094\r\n1.24076 345.267\r\n1.31019 182.165\r\n1.38186 65.6642\r\n1.43337 23.3002\r\n1.45 0\r\n;",
    "source": {
      "file": "AeroTech_J500G.eng",
      "motorId": "5f4294d200023100000001e5",
      "simfileId": "5f4294d20002e9000000029e",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000029e/"
    }
  },
  {
    "eng": "; AeroTech J800T\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ800T 54 314 0 0.613312 1.08595 AT\n   0.040 841.341\n   0.121 818.497\n   0.203 776.386\n   0.285 784.308\n   0.367 785.314\n   0.449 783.315\n   0.531 782.539\n   0.612 779.977\n   0.695 773.680\n   0.777 765.307\n   0.858 755.517\n   0.941 744.777\n   1.023 733.131\n   1.105 719.947\n   1.187 702.235\n   1.269 685.369\n   1.351 668.265\n   1.433 650.327\n   1.515 630.472\n   1.597 615.483\n   1.679 470.262\n   1.760 256.617\n   1.843 108.716\n   1.925 15.005\n   2.007 1.249\n   2.090 0.000",
    "source": {
      "file": "AeroTech_J800T.eng",
      "motorId": "5f4294d20002310000000129",
      "simfileId": "5f4294d20002e9000000005f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000005f/"
    }
  },
  {
    "eng": "K1050W 54 635 1000 1.373 2.259 Aerotech \r\n0 934.5\r\n0.05 1468.5\r\n0.1 1335\r\n0.15 1290.5\r\n0.25 1246\r\n0.75 1246\r\n1.25 1201.5\r\n1.5 1157\r\n1.65 1157\r\n1.75 1246\r\n1.9 890\r\n2.1 578.5\r\n2.2 222.5\r\n2.46 0",
    "source": {
      "file": "AeroTech_K1050W.eng",
      "motorId": "5f4294d2000231000000024e",
      "simfileId": "5f4294d20002e90000000564",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000564/"
    }
  },
  {
    "eng": "; AeroTech K250W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK250W 54 673 0 1.52902 2.21133 AT\n   0.199 365.330\n   0.599 403.324\n   0.999 418.669\n   1.400 409.813\n   1.801 408.949\n   2.201 412.146\n   2.602 411.952\n   3.003 409.488\n   3.403 393.214\n   3.804 373.599\n   4.205 348.913\n   4.605 328.463\n   5.006 307.163\n   5.407 281.467\n   5.807 249.011\n   6.208 217.159\n   6.609 185.908\n   7.009 149.190\n   7.410 119.808\n   7.811 92.096\n   8.211 69.726\n   8.613 52.613\n   9.014 35.876\n   9.414 16.727\n   9.815 4.086\n   10.216 0.000",
    "source": {
      "file": "AeroTech_K250W.eng",
      "motorId": "5f4294d20002310000000132",
      "simfileId": "5f4294d20002e9000000006b",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000006b/"
    }
  },
  {
    "eng": "; AeroTech K550W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK550W 54 410 0 0.919744 1.48736 AT\n   0.065 604.264\n   0.196 642.625\n   0.327 682.197\n   0.458 732.995\n   0.591 758.236\n   0.723 780.289\n   0.854 794.452\n   0.985 797.939\n   1.117 797.601\n   1.249 773.842\n   1.381 711.608\n   1.512 646.522\n   1.644 590.724\n   1.775 537.505\n   1.907 491.012\n   2.040 445.836\n   2.171 401.461\n   2.302 364.291\n   2.433 319.614\n   2.566 255.577\n   2.698 172.573\n   2.829 103.501\n   2.960 51.795\n   3.092 26.814\n   3.224 15.203\n   3.356 0.000\n",
    "source": {
      "file": "AeroTech_K550W.eng",
      "motorId": "5f4294d20002310000000146",
      "simfileId": "5f4294d20002e90000000071",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000071/"
    }
  },
  {
    "eng": "; AeroTech K700W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK700W 54 568 0 1.29158 2.03526 AT\n   0.069 1005.472\n   0.209 1018.916\n   0.350 1026.610\n   0.491 1028.637\n   0.632 1029.337\n   0.773 1004.203\n   0.914 970.694\n   1.055 946.516\n   1.196 918.437\n   1.336 873.783\n   1.478 821.276\n   1.619 773.270\n   1.759 735.553\n   1.900 692.732\n   2.041 658.984\n   2.182 626.737\n   2.323 591.431\n   2.464 508.666\n   2.605 420.175\n   2.746 328.309\n   2.886 202.409\n   3.028 121.672\n   3.169 80.453\n   3.309 50.873\n   3.451 31.548\n   3.593 0.000",
    "source": {
      "file": "AeroTech_K700W.eng",
      "motorId": "5f4294d2000231000000015a",
      "simfileId": "5f4294d20002e90000000079",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000079/"
    }
  },
  {
    "eng": "; per AT announcement 5/8/14\r\nL1000 54 635 18 1.4000000000000001 2.194 AT\r\n   0.004 10.664\r\n   0.011 1268.961\r\n   0.04 1322.279\r\n   0.195 1226.307\r\n   0.249 1268.961\r\n   0.296 1242.303\r\n   0.372 1252.966\r\n   0.416 1215.644\r\n   0.6 1226.307\r\n   0.788 1215.644\r\n   1.066 1183.653\r\n   1.261 1167.658\r\n   1.507 1125.004\r\n   1.746 1087.681\r\n   1.865 1050.359\r\n   1.995 1045.027\r\n   2.093 911.733\r\n   2.158 746.448\r\n   2.263 554.504\r\n   2.389 405.215\r\n   2.577 191.944\r\n   2.693 85.308\r\n   2.761 42.654\r\n   3.0 0.0",
    "source": {
      "file": "AeroTech_L1000.eng",
      "motorId": "5f4294d2000231000000040b",
      "simfileId": "5f4294d20002e900000007f6",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007f6/"
    }
  },
  {
    "eng": "; AeroTech L952W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nL952W 98 427 0 2.73011 5.01222 AT\n   0.141 679.073\n   0.425 801.562\n   0.709 848.474\n   0.994 913.345\n   1.278 981.614\n   1.562 1043.690\n   1.847 1088.114\n   2.131 1112.556\n   2.416 1121.541\n   2.700 1118.573\n   2.984 1100.665\n   3.269 1039.140\n   3.553 965.784\n   3.837 876.793\n   4.122 780.693\n   4.406 693.903\n   4.691 608.030\n   4.975 528.335\n   5.259 463.528\n   5.544 405.769\n   5.828 358.367\n   6.112 279.009\n   6.397 99.897\n   6.681 20.108\n   6.967 3.317\n   7.252 0.000",
    "source": {
      "file": "AeroTech_L952W.eng",
      "motorId": "5f4294d20002310000000185",
      "simfileId": "5f4294d20002e90000000085",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000085/"
    }
  },
  {
    "eng": "N3300R-P 98 1060 P 7.5120000000000005 12.269 AT\r\n   0.036 40.168\r\n   0.078 2887.624\r\n   0.125 3775.78\r\n   0.157 3628.498\r\n   0.2 3534.773\r\n   0.417 3597.256\r\n   0.666 3628.498\r\n   0.962 3668.666\r\n   1.197 3664.203\r\n   1.507 3655.276\r\n   1.9 3619.572\r\n   2.206 3570.478\r\n   2.423 3530.31\r\n   2.637 3423.195\r\n   3.008 3208.967\r\n   3.318 3025.98\r\n   3.617 2820.677\r\n   3.86 2646.617\r\n   3.963 2597.522\r\n   4.024 2468.093\r\n   4.091 2267.253\r\n   4.163 1896.816\r\n   4.284 1124.7\r\n   4.394 343.658\r\n   4.455 129.43\r\n   4.519 0.0",
    "source": {
      "file": "AeroTech_N3300.eng",
      "motorId": "5f4294d2000231000000030d",
      "simfileId": "5f4294d20002e90000000884",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000884/"
    }
  },
  {
    "eng": "; Pro-54-3G White Thunder\r\n1266-J760-WT-19A 54 329 8-10-12-14-16-18-19 0.5760 1.0768 CTI\r\n   0.012 600.251\r\n   0.019 833.333\r\n   0.026 938.596\r\n   0.04 794.486\r\n   0.054 756.892\r\n   0.094 778.195\r\n   0.129 800.752\r\n   0.165 813.283\r\n   0.218 825.815\r\n   0.279 830.827\r\n   0.377 835.84\r\n   0.496 837.093\r\n   0.617 829.574\r\n   0.709 819.549\r\n   0.811 802.005\r\n   0.917 785.714\r\n   1.041 764.411\r\n   1.201 750.627\r\n   1.331 741.855\r\n   1.455 729.323\r\n   1.488 729.323\r\n   1.514 735.589\r\n   1.556 749.373\r\n   1.568 729.323\r\n   1.575 665.414\r\n   1.589 533.835\r\n   1.616 327.068\r\n   1.646 122.807\r\n   1.659 72.682\r\n   1.681 30.075\r\n   1.713 6.266\r\n   1.731 0.0",
    "source": {
      "file": "Cesaroni_1266-J760-WT-19A.eng",
      "motorId": "5f4294d200023100000003a8",
      "simfileId": "5f4294d20002e9000000074a",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000074a/"
    }
  },
  {
    "eng": ";\n;\nK660  54.0 572.00 7-17 1.17700 1.94900 CTI\n   0.07    1078.90 \n   0.23    1006.47 \n   0.40     966.76 \n   0.80     897.52 \n   1.20     842.72 \n   1.60     794.15 \n   2.01     744.52 \n   2.40     692.27 \n   2.54     671.37 \n   2.68     439.08 \n   2.80     400.68 \n   3.01     386.90 \n   3.20     234.31 \n   3.45     106.65 \n   3.60      44.03 \n   3.69       0.00\n",
    "source": {
      "file": "Cesaroni_2437K660-17A.eng",
      "motorId": "5f4294d20002310000000154",
      "simfileId": "5f4294d20002e90000000143",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000143/"
    }
  },
  {
    "eng": "; CTI Pro54-2G 838 J293BS 13A\nJ293BS 54 237 13-12-11-10-9-8-7-6-5-4-3 0.41600000000000004 0.84 CTI\n   0.019 22.847\n   0.032 250.277\n   0.044 386.32\n   0.06 302.202\n   0.073 256.508\n   0.13 285.586\n   0.266 309.471\n   0.487 318.818\n   0.734 325.049\n   1.432 324.01\n   1.786 309.471\n   2.074 294.933\n   2.33 280.394\n   2.488 273.124\n   2.58 272.086\n   2.634 258.585\n   2.713 163.044\n   2.795 70.618\n   2.852 20.77\n   2.896 0.0\n",
    "source": {
      "file": "Cesaroni_838J293-13A.eng",
      "motorId": "5f4294d200023100000002d8",
      "simfileId": "5f4294d20002e90000000674",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000674/"
    }
  },
  {
    "eng": "I216-CL(I) 38 367 5-7-9-11-14 0.3125 0.601 CTI\r\n0.017 35\r\n0.03 300\r\n0.035 345\r\n0.05 325\r\n0.07 275\r\n0.14 292\r\n0.26 296\r\n0.8 280\r\n1.1 280.4\r\n1.62 255\r\n1.8 226\r\n2.105 210\r\n2.2 195\r\n2.45 80\r\n2.75 36\r\n3.1 0",
    "source": {
      "file": "Cesaroni_I216.eng",
      "motorId": "5f4294d200023100000002cc",
      "simfileId": "5f4294d20002e90000000654",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000654/"
    }
  },
  {
    "eng": ";\n;\nI540WT 38 367 7-9-11-13-16 0.3288 0.5982 CTI \n0.03 597.86\n0.04 611.31\n0.06 605.64\n0.12 612.36\n0.24 624.54\n0.36 626\n0.48 623.63\n0.6 616.42\n0.72 598.14\n0.84 583.16\n0.95 568.92\n0.96 558.53\n0.98 533.45\n1.02 436.53\n1.06 303.15\n1.09 184.92\n1.13 74.27\n1.18 0",
    "source": {
      "file": "Cesaroni_I540WT.eng",
      "motorId": "5f4294d200023100000001fb",
      "simfileId": "5f4294d20002e900000002aa",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000002aa/"
    }
  },
  {
    "eng": "; 644-J94-MY  Cesaroni Pro38\n; converted from the ThrustCurve.org RockSim simfile (no RASP file is published)\n644-J94-MY-P 38 367 0 0.3930 0.6600 CTI\n   0.0000 0.000\n   0.0050 19.477\n   0.0140 168.646\n   0.0500 133.967\n   0.1130 133.967\n   0.2030 146.081\n   0.7520 133.967\n   1.7870 116.865\n   3.0750 110.451\n   4.2360 108.314\n   4.8030 77.672\n   5.4740 56.295\n   6.3750 17.577\n   6.8790 6.413\n   6.9280 0.000\n",
    "source": {
      "file": "Cesaroni_J94.eng",
      "motorId": "5f4294d20002310000000416",
      "simfileId": "5f4294d20002e90000000810",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000810/"
    }
  },
  {
    "eng": "; From Cesaroni WebPage by C. Kobel 4/23/15\nK1440WT 54 572 8-11-14-17 1.129 1.893 Ces\n   0.015 893.963\n   0.026 1563.355\n   0.030 1671.321\n   0.035 1718.827\n   0.047 1667.003\n   0.063 1628.135\n   0.100 1671.321\n   0.200 1701.552\n   0.300 1705.871\n   0.400 1710.189\n   0.500 1705.871\n   0.600 1701.552\n   0.700 1684.277\n   0.800 1658.366\n   0.900 1619.498\n   1.000 1597.904\n   1.100 1546.080\n   1.221 1498.575\n   1.300 1144.445\n   1.337 1062.39\n   1.400 1058.072\n   1.447 1053.753\n   1.500 716.898\n   1.543 578.700\n   1.600 306.625\n   1.644 125.241\n   1.700 0.0\n",
    "source": {
      "file": "Cesaroni_K1440.eng",
      "motorId": "5f4294d20002310000000261",
      "simfileId": "5f4294d20002e90000000852",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000852/"
    }
  },
  {
    "eng": "; Pro-54-5G White Long Burn Plugged\n2021-K261-WH_LB-P 54 488 P 1.1519 1.9317 CTI\n   0.035 283.061\n   0.069 321.706\n   0.124 345.797\n   0.228 336.763\n   0.525 347.302\n   0.85 359.348\n   1.334 356.336\n   1.79 359.348\n   2.039 354.329\n   2.412 353.325\n   2.793 349.812\n   3.131 344.291\n   3.774 323.714\n   4.652 278.545\n   5.281 230.866\n   5.571 206.775\n   5.993 166.625\n   6.325 137.516\n   6.615 102.384\n   7.085 55.207\n   7.362 35.634\n   7.694 20.577\n   8.129 9.536\n   8.502 2.509\n   8.979 0.0\n",
    "source": {
      "file": "Cesaroni_K261.eng",
      "motorId": "5f4294d200023100000003a6",
      "simfileId": "5f4294d20002e9000000074e",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000074e/"
    }
  },
  {
    "eng": ";\n;\nK445  54.0 404.00 7-17 0.79200 1.39800 CTI\n   0.05     664.83 \n   0.19     640.68 \n   0.48     622.98 \n   1.00     576.29 \n   1.51     515.12 \n   2.00     442.68 \n   2.50     392.26 \n   3.02     350.93 \n   3.13     339.66 \n   3.31     210.88 \n   3.47      78.88 \n   3.67       0.00",
    "source": {
      "file": "Cesaroni_K445.eng",
      "motorId": "5f4294d2000231000000013b",
      "simfileId": "5f4294d20002e90000000141",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000141/"
    }
  },
  {
    "eng": ";\n;\nK530SS  54.0 404.00 6-16 1.02500 1.63980 CTI\n   0.05     533.59 \n   0.09     503.98 \n   0.29     514.09 \n   0.60     534.31 \n   0.90     557.41 \n   1.20     577.63 \n   1.50     587.74 \n   1.80     596.40 \n   2.10     535.44 \n   2.31     502.54 \n   2.47     551.63 \n   2.56     393.94 \n   2.60     274.37 \n   2.64     137.19 \n   2.67       0.00\n",
    "source": {
      "file": "Cesaroni_K530.eng",
      "motorId": "5f4294d20002310000000145",
      "simfileId": "5f4294d20002e90000000147",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000147/"
    }
  },
  {
    "eng": "; C-Star 75mm 3G\n; 4263-L1350-CS-P\n4263-L1350-CS-P 75 486 P 2.0245 3.5707 CTI\n   0.016 1421.724\n   0.034 1345.218\n   0.049 1502.479\n   0.081 1415.348\n   0.21 1432.349\n   0.453 1432.349\n   0.809 1462.102\n   1.07 1534.357\n   1.28 1540.732\n   2.661 1283.589\n   2.843 1277.214\n   2.932 1115.702\n   3.037 488.784\n   3.163 82.881\n   3.284 0.0\n",
    "source": {
      "file": "Cesaroni_L1350.eng",
      "motorId": "5f4294d200023100000003dc",
      "simfileId": "5f4294d20002e900000007c6",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007c6/"
    }
  },
  {
    "eng": ";\n;\nL730  54.0 649.00 0 1.35100 2.24700 CTI\n   0.00      81.36 \n   0.01    1079.71 \n   0.02    1216.59 \n   0.04    1154.68 \n   0.20    1127.51 \n   0.45    1055.11 \n   0.60    1028.17 \n   0.75     995.24 \n   1.00     959.33 \n   1.50     898.71 \n   2.00     830.70 \n   2.50     730.76 \n   2.60     592.55 \n   2.70     510.96 \n   2.90     487.88 \n   3.00     405.72 \n   3.10     299.80 \n   3.20     296.09 \n   3.30     251.85 \n   3.40     171.70 \n   3.50     165.26 \n   3.60     139.38 \n   3.65     117.77 \n   3.77      45.38 \n   3.77       0.00\n",
    "source": {
      "file": "Cesaroni_L730.eng",
      "motorId": "5f4294d2000231000000017c",
      "simfileId": "5f4294d20002e90000000144",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000144/"
    }
  },
  {
    "eng": "M1670-BS 75 757 0 3.101 5.231 CTI \n0.055 100\n0.092 1500\n0.1 2000\n0.15 2200\n0.2 1800\n0.5 1950\n1 2034\n1.5 2000\n2 1900\n2.5 1760\n2.9 1700\n3 1650\n3.3 530\n3.4 350\n3.9 0\n",
    "source": {
      "file": "Cesaroni_M1670.eng",
      "motorId": "5f4294d20002310000000296",
      "simfileId": "5f4294d20002e9000000062c",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000062c/"
    }
  },
  {
    "eng": "; Imax Pro75 6GXL\n; 9977 M2245-IM-P\n9977-M2245-IM-P 75 1025 P 5.309 8.182 CTI\n   0.043 3045.655\n   0.136 2629.813\n   1.393 3003.3\n   2.168 3007.151\n   2.708 2972.497\n   2.837 2883.938\n   3.152 1955.996\n   3.397 1409.241\n   3.878 562.156\n   4.371 0.0\n",
    "source": {
      "file": "Cesaroni_M2245.eng",
      "motorId": "5f4294d200023100000003e9",
      "simfileId": "5f4294d20002e900000007b5",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007b5/"
    }
  },
  {
    "eng": "; Pro98-4G 9994M3400-WT P\nM3400-WT 98 702 P 4.766 8.108 CTI\n   0.021 3639.453\n   0.049 3360.146\n   0.111 3300.899\n   0.374 3478.64\n   0.909 3774.874\n   1.059 3897.6\n   1.208 3884.904\n   1.571 3787.57\n   2.168 3402.465\n   2.467 3245.884\n   2.709 3292.435\n   2.734 3254.348\n   2.821 1032.589\n   2.876 550.15\n   2.93 165.045\n   2.99 0.0\n",
    "source": {
      "file": "Cesaroni_M3400.eng",
      "motorId": "5f4294d20002310000000318",
      "simfileId": "5f4294d20002e900000006f9",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006f9/"
    }
  },
  {
    "eng": "; Pro98-6GXL 14263N3400-SK P\r\nN3400-SK 98 1239 P 8.471 13.972 CTI\r\n   0.055 3602.205\r\n   0.177 3060.167\r\n   0.608 3397.34\r\n   1.537 3811.337\r\n   2.252 3973.522\r\n   2.86 3760.121\r\n   3.152 3597.937\r\n   3.545 3346.124\r\n   3.71 3627.813\r\n   3.837 2868.106\r\n   3.884 1907.803\r\n   3.999 1510.877\r\n   4.188 273.153\r\n   4.28 81.092\r\n   4.3 0.0",
    "source": {
      "file": "Cesaroni_N3400.eng",
      "motorId": "5f4294d200023100000002f9",
      "simfileId": "5f4294d20002e900000006c2",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006c2/"
    }
  },
  {
    "eng": "; Pro98-6GXL 17631N3800-BS P\r\nN3800-BS 98 1239 P 8.71 14.261000000000001 CTI\r\n   0.016 2671.724\r\n   0.069 4632.012\r\n   0.159 4360.745\r\n   0.293 4355.626\r\n   1.11 4591.066\r\n   1.48 4703.667\r\n   1.847 4729.258\r\n   2.384 4683.194\r\n   2.628 4550.12\r\n   3.141 4135.542\r\n   3.343 4043.413\r\n   3.434 4022.94\r\n   3.497 3787.501\r\n   3.582 3204.021\r\n   3.681 2809.916\r\n   3.853 2385.102\r\n   4.042 1458.7\r\n   4.198 972.467\r\n   4.338 946.875\r\n   4.401 864.983\r\n   4.604 378.75\r\n   4.673 230.321\r\n   4.7 0.0",
    "source": {
      "file": "Cesaroni_N3800.eng",
      "motorId": "5f4294d20002310000000319",
      "simfileId": "5f4294d20002e900000006fb",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006fb/"
    }
  },
  {
    "eng": ";Estes A10T RASP.ENG file made from NAR published data\n; File produced March 3, 2011\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nA10T 13 45 0 .0038 .00525 E\n0.016 0.492\n0.040 0.752\n0.062 0.962\n0.078 2.051\n0.096 2.858\n0.122 4.611\n0.138 6.054\n0.162 8.100\n0.180 9.502\n0.198 9.740\n0.212 8.204\n0.224 4.530\n0.238 2.054\n0.268 1.414\n0.292 1.385\n0.324 1.067\n0.364 1.099\n0.396 0.957\n0.446 0.995\n0.490 0.901\n0.574 0.909\n0.676 0.909\n0.782 1.031\n0.886 1.048\n0.980 1.029\n1.006 0.995\n1.038 1.049\n1.050 0.741\n1.060 0.000\n",
    "source": {
      "file": "Estes_A10.eng",
      "motorId": "5f4294d2000231000000000c",
      "simfileId": "624aff26a49a690004b83002",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/624aff26a49a690004b83002/"
    }
  },
  {
    "eng": ";\r\n;Estes A8 RASP.ENG file made from NAR published data\r\n;File produced October 3, 2000\r\n;The total impulse, peak thrust, average thrust and burn time are\r\n;the same as the averaged static test data on the NAR web site in\r\n;the certification file. The curve drawn with these data points is as\r\n;close to the certification curve as can be with such a limited\r\n;number of points (32) allowed with wRASP up to v1.6.\r\nA8 18 70 3-5 0.0033 0.01635 Estes \r\n0.041 0.512\r\n0.084 2.115\r\n0.127 4.358\r\n0.166 6.794\r\n0.192 8.588\r\n0.206 9.294\r\n0.226 9.73\r\n0.236 8.845\r\n0.247 7.179\r\n0.261 5.063\r\n0.277 3.717\r\n0.306 3.205\r\n0.351 2.884\r\n0.405 2.499\r\n0.467 2.371\r\n0.532 2.307\r\n0.589 2.371\r\n0.632 2.371\r\n0.652 2.243\r\n0.668 1.794\r\n0.684 1.153\r\n0.703 0.448\r\n0.73 0",
    "source": {
      "file": "Estes_A8.eng",
      "motorId": "5f4294d2000231000000000b",
      "simfileId": "5f4294d20002e900000004e3",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e3/"
    }
  },
  {
    "eng": "; B4-4\nB4-4 18 70 P 0.006 0.0195 E\n   0.058 2.361\n   0.102 2.921\n   0.122 3.797\n   0.15 5.866\n   0.18 8.373\n   0.199 9.882\n   0.208 10.88\n   0.216 11.367\n   0.238 11.245\n   0.245 10.832\n   0.262 8.982\n   0.293 6.134\n   0.322 5.306\n   0.357 4.917\n   0.388 4.795\n   0.416 4.746\n   0.46 4.625\n   0.502 4.576\n   0.544 4.357\n   0.575 4.503\n   0.605 4.527\n   0.674 4.552\n   0.731 4.454\n   0.88 4.454\n   0.915 4.503\n   0.96 4.406\n   1.0 4.065\n   1.047 2.556\n   1.049 0.0\n",
    "source": {
      "file": "Estes_B4.eng",
      "motorId": "5f4294d2000231000000000e",
      "simfileId": "5f4294d20002e90000000834",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000834/"
    }
  },
  {
    "eng": "; Estes B6-0 from NAR data by Mark Koelsch\nB6-0 18 70 0 0.0056 0.0156 E\n   0.036 1.364\n   0.064 2.727\n   0.082 4.215\n   0.111 6.694\n   0.135 9.05\n   0.146 9.545\n   0.172 11.901\n   0.181 12.149\n   0.191 11.901\n   0.211 9.174\n   0.239 7.314\n   0.264 6.074\n   0.275 5.95\n   0.333 5.207\n   0.394 4.835\n   0.445 4.835\n   0.556 4.339\n   0.667 4.587\n   0.723 4.339\n   0.78 4.339\n   0.793 4.091\n   0.812 2.603\n   0.833 1.24\n   0.857 0.0\n",
    "source": {
      "file": "Estes_B6.eng",
      "motorId": "5f4294d20002310000000010",
      "simfileId": "5f4294d20002e90000000414",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000414/"
    }
  },
  {
    "eng": ";\n;ESTES C11 RASP.ENG file made from NAR published data\n;File produced JANUARY 1, 2002\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nC11 24 70 0-3-5-7 0.012 0.0353 Estes \n0.034 1.692\n0.066 3.782\n0.107 7.566\n0.145 10.946\n0.183 14.832\n0.214 17.618\n0.226 18.213\n0.256 20.107\n0.281 21.208\n0.298 21.73\n0.306 20.206\n0.323 17.321\n0.337 14.931\n0.358 13.236\n0.385 11.947\n0.413 11.65\n0.468 10.946\n0.539 10.45\n0.619 10.648\n0.683 10.648\n0.715 10.648\n0.726 10.053\n0.74 8.163\n0.758 5.773\n0.778 3.185\n0.795 1.394\n0.81 0\n",
    "source": {
      "file": "Estes_C11.eng",
      "motorId": "5f4294d2000231000000001a",
      "simfileId": "5f4294d20002e900000004e8",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e8/"
    }
  },
  {
    "eng": "; Estes C6 RASP.ENG file made from NAR published data\n; File produced October 3, 2000\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nC6 18 70 0-3-5-7 .0108 .0231 E\n0.031 0.946\n0.092 4.826\n0.139 9.936\n0.192 14.090\n0.209 11.446\n0.231 7.381\n0.248 6.151\n0.292 5.489\n0.370 4.921\n0.475 4.448\n0.671 4.258\n0.702 4.542\n0.723 4.164\n0.850 4.448\n1.063 4.353\n1.211 4.353\n1.242 4.069\n1.303 4.258\n1.468 4.353\n1.656 4.448\n1.821 4.448\n1.834 2.933\n1.847 1.325\n1.860 0.000\n",
    "source": {
      "file": "Estes_C6.eng",
      "motorId": "5f4294d20002310000000015",
      "simfileId": "69eb2379c7d63000021d8c29",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/69eb2379c7d63000021d8c29/"
    }
  },
  {
    "eng": ";\n;Estes D12 RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD12 24 70 0-3-5-7 0.0211 0.0426 Estes \n0.049 2.569\n0.116 9.369\n0.184 17.275\n0.237 24.258\n0.282 29.73\n0.297 27.01\n0.311 22.589\n0.322 17.99\n0.348 14.126\n0.386 12.099\n0.442 10.808\n0.546 9.876\n0.718 9.306\n0.879 9.105\n1.066 8.901\n1.257 8.698\n1.436 8.31\n1.59 8.294\n1.612 4.613\n1.65 0\n",
    "source": {
      "file": "Estes_D12.eng",
      "motorId": "5f4294d20002310000000020",
      "simfileId": "5f4294d20002e900000004ea",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004ea/"
    }
  },
  {
    "eng": "; Based on NAR Published Data, 7/31/12, C. J. Kobel\nE12 24 95 0-4-6-8 0.0359 0.0599 Estes\n   0.052 5.045\n   0.096 9.910\n   0.196 24.144\n   0.251 31.351\n   0.287 32.973\n   0.300 29.910\n   0.344 17.117\n   0.370 14.414\n   0.400 12.973\n   0.500 11.712\n   0.600 11.171\n   0.700 10.631\n   0.800 10.09\n   0.900 9.73\n   1.000 9.55\n   1.101 9.91\n   1.200 9.55\n   1.300 9.73\n   1.400 9.73\n   1.500 9.73\n   1.600 9.73\n   1.700 9.55\n   1.800 9.73\n   1.900 9.73\n   2.000 9.55\n   2.100 9.55\n   2.200 9.73\n   2.300 9.19\n   2.375 9.37\n   2.400 5.95\n   2.440 0.0\n",
    "source": {
      "file": "Estes_E12.eng",
      "motorId": "5f4294d200023100000003e3",
      "simfileId": "5f4294d20002e900000007ad",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007ad/"
    }
  },
  {
    "eng": "; Estes E9-0 by Mark Koelsch from NAR data\nE9-0 24 95 0 0.0358 0.056799999999999996 E\n   0.046 1.913\n   0.235 16.696\n   0.273 18.435\n   0.326 14.957\n   0.38 12.174\n   0.44 10.435\n   0.835 9.043\n   1.093 8.87\n   1.496 8.696\n   1.997 8.696\n   2.498 8.696\n   3.014 9.217\n   3.037 5.043\n   3.067 1.217\n   3.09 0.0\n",
    "source": {
      "file": "Estes_E9.eng",
      "motorId": "5f4294d20002310000000028",
      "simfileId": "5f4294d20002e90000000416",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000416/"
    }
  },
  {
    "eng": "G66LR 38 122.2 5-15 0.07200000000000001 0.25 Loki\r\n   0.01 4.448\r\n   0.027 3.14\r\n   0.051 12.298\r\n   0.07 22.764\r\n   0.092 45.006\r\n   0.104 66.723\r\n   0.111 80.068\r\n   0.13 89.488\r\n   0.145 97.861\r\n   0.176 106.496\r\n   0.21 112.252\r\n   0.246 114.607\r\n   0.287 115.654\r\n   0.359 113.299\r\n   0.506 106.757\r\n   0.598 102.571\r\n   0.757 94.721\r\n   1.006 80.853\r\n   1.196 66.462\r\n   1.473 44.482\r\n   1.51 41.081\r\n   1.691 26.428\r\n   1.763 21.456\r\n   1.823 16.746\r\n   1.879 14.13\r\n   2.016 7.326\r\n   2.091 4.448\r\n   2.117 4.71\r\n   2.129 0.0",
    "source": {
      "file": "Loki_G66.eng",
      "motorId": "5f4294d20002310000000449",
      "simfileId": "5f4294d20002e90000000864",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000864/"
    }
  },
  {
    "eng": ";\nJ528 38 406 5-8-10-13-17 0.372 0.752 Loki \n0.01 704.2\n0.02 1019\n0.03 983.9\n0.05 881.1\n0.1 797.5\n0.15 771.7\n0.17 765.72\n0.21 765.72\n0.25 778.2\n0.42 789.28\n0.51 771.61\n0.6 756.89\n0.66 751\n0.71 762.78\n0.76 697.99\n0.8 665.59\n0.84 612.58\n0.92 488.88\n0.95 385.81\n1.02 282.73\n1.06 179.65\n1.14 53.01\n1.19 35.34\n1.23 32.2\n1.25 0\n",
    "source": {
      "file": "Loki_J528.eng",
      "motorId": "5f4294d20002310000000123",
      "simfileId": "5f4294d20002e90000000127",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000127/"
    }
  },
  {
    "eng": "K1127LB 38 625.5 P 0.624 1.172 Loki\r\n   0.009 77.978\r\n   0.021 1002.962\r\n   0.033 1368.654\r\n   0.045 1210.008\r\n   0.058 1365.965\r\n   0.067 1263.786\r\n   0.08 1360.587\r\n   0.092 1255.719\r\n   0.105 1331.009\r\n   0.117 1242.275\r\n   0.13 1312.186\r\n   0.142 1261.097\r\n   0.155 1304.12\r\n   0.167 1261.097\r\n   0.218 1290.675\r\n   0.395 1325.631\r\n   0.542 1368.654\r\n   0.689 1392.854\r\n   0.726 1382.098\r\n   0.755 1344.453\r\n   0.814 1110.518\r\n   0.867 949.184\r\n   0.874 1099.763\r\n   0.883 962.629\r\n   0.908 847.006\r\n   0.989 548.537\r\n   0.997 363.002\r\n   1.003 715.249\r\n   1.014 494.759\r\n   1.048 406.025\r\n   1.091 352.247\r\n   1.152 228.557\r\n   1.198 158.645\r\n   1.244 69.912\r\n   1.286 32.267\r\n   1.37 0.0",
    "source": {
      "file": "Loki_K1127.eng",
      "motorId": "5f4294d2000231000000043a",
      "simfileId": "5f4294d20002e90000000836",
      "license": "free",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000836/"
    }
  },
  {
    "eng": "; 38/1200\nK627LR 38 625.5 5-7-11-14 0.6880000000000001 1.236 Loki\n   0.014 735.02\n   0.034 989.33\n   0.073 983.128\n   0.166 905.594\n   0.298 840.465\n   0.501 806.351\n   0.746 815.655\n   1.002 824.959\n   1.193 843.567\n   1.258 849.77\n   1.303 831.161\n   1.348 784.641\n   1.5 669.891\n   1.756 437.29\n   1.951 276.02\n   2.004 245.007\n   2.086 210.892\n   2.142 182.98\n   2.252 105.446\n   2.322 74.432\n   2.443 49.622\n   2.499 27.912\n   2.564 0.0\n",
    "source": {
      "file": "Loki_K627.eng",
      "motorId": "5f4294d20002310000000446",
      "simfileId": "5f4294d20002e90000000861",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000861/"
    }
  },
  {
    "eng": ";\n;\nL1400 54 726 0 1.4 2.54 Loki \n0.00580046 1606.3\n0.11891 1535.7\n0.327726 1535.7\n0.49884 1588.65\n1.00058 1782.82\n1.40661 1906.38\n1.49942 1376.83\n1.60673 953.19\n1.74594 547.202\n1.90545 335.382\n1.99826 211.82\n2 0\n",
    "source": {
      "file": "Loki_L1400.eng",
      "motorId": "5f4294d20002310000000193",
      "simfileId": "5f4294d20002e9000000012c",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000012c/"
    }
  },
  {
    "eng": ";\n;\nM1882 75 785 0 3.12979 5.53383 Loki \n0.01 4.8\n0.0174014 2579.22\n0.0696056 2392.32\n0.232019 2298.87\n0.50464 2261.49\n0.771462 2298.87\n0.986079 2411.01\n1.1891 2579.22\n1.49652 2597.91\n1.72854 2485.77\n2.00116 2354.94\n2.5 1644.72\n2.99884 242.97\n3.25 0\n",
    "source": {
      "file": "Loki_M1882.eng",
      "motorId": "5f4294d200023100000001ae",
      "simfileId": "5f4294d20002e9000000012b",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000012b/"
    }
  },
  {
    "eng": "M2550-LB 76 785 0 3.13 5.53 Loki \n0.00776398 2974.14\n0.0621118 2887.93\n0.427019 2887.93\n0.861801 3017.24\n1.49845 2974.14\n2.11957 2413.79\n2.45342 474.138\n2.6 0\n",
    "source": {
      "file": "Loki_M2550.eng",
      "motorId": "5f4294d2000231000000024f",
      "simfileId": "5f4294d20002e900000005df",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000005df/"
    }
  },
  {
    "eng": "; Quest C6-0 from NAR data\nC6-0 18 70 0 0.0083 0.0216 Q\n   0.02 0.497\n   0.057 2.539\n   0.089 5.132\n   0.129 7.947\n   0.159 9.437\n   0.171 21.247\n   0.181 23.234\n   0.194 22.958\n   0.204 22.185\n   0.218 19.592\n   0.233 17.881\n   0.258 10.486\n   0.308 2.428\n   0.338 2.539\n   0.385 2.98\n   0.412 3.091\n   0.442 3.422\n   0.459 2.98\n   0.536 3.256\n   0.732 3.311\n   0.747 2.483\n   0.78 2.98\n   1.323 3.587\n   1.365 2.815\n   1.887 3.808\n   1.974 3.256\n   2.1 3.532\n   2.227 3.201\n   2.247 0.0\n",
    "source": {
      "file": "Quest_C6.eng",
      "motorId": "5f4294d20002310000000016",
      "simfileId": "5f4294d20002e9000000041c",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000041c/"
    }
  }
];
