// GENERATED by scripts/gen-motors.mjs — do not edit by hand.
//
// The bundled offline motor database: authentic RASP thrust curves from ThrustCurve.org,
// inlined verbatim so the simulator resolves motors client-side with no network. Thrust-vs-
// time is factual certification / test-stand data; each entry records its ThrustCurve.org
// simfile id, info URL, and license for auditability. Regenerate with:
//   node scripts/gen-motors.mjs

export interface CatalogSource {
  file: string;
  motorId: string | null;
  simfileId: string | null;
  license: string | null;
  infoUrl: string | null;
  /** ThrustCurve.org's designation for this motor, when recorded — the catalogued identity
   *  matching runs against, in preference to the RASP header's abbreviation. */
  designation: string | null;
  /** ThrustCurve.org's manufacturer, likewise, in preference to the header's maker code. */
  manufacturer: string | null;
  /** ThrustCurve.org's common (class-and-thrust) name, e.g. "J285" for part number
   *  "648J285-15A" — the other published name a design file may reference. */
  commonName: string | null;
}

export interface CatalogEntry {
  /** Raw RASP .eng text, parsed at load by lib/motors/eng.ts. */
  eng: string;
  source: CatalogSource;
}

export const MOTOR_CATALOG: CatalogEntry[] = [
  {
    "eng": ";\n;AMW L1100 RASP.ENG file made from NAR published data\n;File produced April 19, 2004\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nL1100RR 75 728 100 1.346 2.5881 Animal_Motor_Works \n0.013 681.489\n0.029 1116.88\n0.041 1196.3\n0.079 1210.38\n0.147 1203.34\n0.257 1218.42\n0.366 1225.45\n0.567 1254.61\n0.824 1282.76\n1.059 1311.91\n1.267 1340.23\n1.459 1311.91\n1.622 1297.84\n1.713 1290.8\n1.785 1268.68\n1.83 1218.42\n1.886 1080.69\n1.969 819.214\n2.048 558.24\n2.108 376.985\n2.156 246.498\n2.205 144.963\n2.269 72.501\n2.35 0",
    "source": {
      "file": "AMW_L1100.eng",
      "motorId": "5f4294d2000231000000018b",
      "simfileId": "5f4294d20002e90000000482",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000482/",
      "designation": "L1100RR",
      "manufacturer": "Animal Motor Works",
      "commonName": null
    }
  },
  {
    "eng": ";Aerotech D21 RASP.ENG file made from NAR published data\n;File produced July 4, 2000\n;Submitted to ThrustCurve.org by Chris Kobel (3/29/07)\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD21T 18 70 4-7 0.0096 0.025 AT \n   0.01   1.367\n   0.021 19.367\n   0.029 32.12\n   0.037 31.667\n   0.051 30.528\n   0.094 30.074\n   0.115 31.213\n   0.133 30.074\n   0.177 30.76\n   0.189 29.842\n   0.203 30.528\n   0.226 29.842\n   0.275 28.935\n   0.296 29.389\n   0.331 28.027\n   0.421 25.971\n   0.478 24.146\n   0.579 20.728\n   0.659 17.774\n   0.739 14.356\n   0.799  9.569\n   0.852  4.557\n   0.899  1.139\n   0.94   0\n",
    "source": {
      "file": "AeroTech_D21T.eng",
      "motorId": "5f4294d20002310000000023",
      "simfileId": "5f4294d20002e9000000027d",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000027d/",
      "designation": "D21T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; Aerotech E30 RASP.ENG file made from NAR published data\n; File produced Sept 30, 2010\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nE30 24 70 4-7 .0178 .047 A\n0.006 49.3000\n0.030 45.7010\n0.038 47.1810\n0.050 45.1800\n0.062 43.7010\n0.112 43.4020\n0.138 42.8170\n0.206 42.0730\n0.238 43.3680\n0.282 41.5750\n0.324 41.0860\n0.342 41.7330\n0.362 40.1680\n0.436 38.1580\n0.524 36.3980\n0.650 32.9720\n0.712 31.0500\n0.836 25.0770\n0.874 22.4750\n0.888 21.5080\n0.900 20.0080\n0.912 17.1760\n0.924 13.3000\n0.942 6.6500\n0.962 2.7550\n0.974 1.6370\n0.988 0.7810\n1.000 0.4290\n1.010 0.1410\n1.020 0.0000\n",
    "source": {
      "file": "AeroTech_E30T.eng",
      "motorId": "5f4294d20002310000000034",
      "simfileId": "62431a34ee302a00044520da",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/62431a34ee302a00044520da/",
      "designation": "E30T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Aerotech F50 RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case F50T motors.\nF50T 29 98 4-6-9 0.0336 0.0898 AeroTech\n0.013 73.762\n0.0326 70.383\n0.267 69.82\n0.518 67.005\n0.792 56.87\n0.906 50.676\n1 44.482\n1.036 39.978\n1.107 23.649\n1.199 6.194\n1.316 1.126\n1.43 0\n",
    "source": {
      "file": "AeroTech_F50T.eng",
      "motorId": "5f4294d20002310000000049",
      "simfileId": "5f4294d20002e9000000045b",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000045b/",
      "designation": "F50T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Aerotech F52 RASP.ENG file made from NAR published data\n;File produced July 4, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nF52 29 124 5-8-11 0.0366 0.1214 AT\n0.012 46.899\n0.033 61.778\n0.056 69.441\n0.097 73.483\n0.115 76.636\n0.13 74.381\n0.153 74.82\n0.168 78.422\n0.182 78.95\n0.206 77.963\n0.238 77.504\n0.258 73.892\n0.314 72.974\n0.39 72.046\n0.428 70.679\n0.501 65.699\n0.565 62.975\n0.688 58.874\n0.749 56.15\n0.837 52.517\n0.901 49.793\n0.971 46.161\n1.088 39.365\n1.144 34.386\n1.173 29.417\n1.222 20.376\n1.275 13.151\n1.339 5.461\n1.389 1.838\n1.42 0",
    "source": {
      "file": "AeroTech_F52T.eng",
      "motorId": "5f4294d2000231000000004b",
      "simfileId": "5f4294d20002e9000000045c",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000045c/",
      "designation": "F52",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "F67W 29 83 4-6-9 0.03 0.08 AT\n   0.002 66.662\n   0.008 71.441\n   0.016 74.505\n   0.039 77.936\n   0.068 80.632\n   0.099 82.592\n   0.148 84.43\n   0.201 85.533\n   0.257 86.146\n   0.298 86.023\n   0.399 84.185\n   0.483 82.96\n   0.499 82.347\n   0.568 80.019\n   0.601 78.794\n   0.625 77.936\n   0.654 78.058\n   0.672 75.853\n   0.687 71.073\n   0.7 67.52\n   0.714 62.005\n   0.731 53.06\n   0.748 44.482\n   0.764 35.659\n   0.778 26.836\n   0.789 20.954\n   0.797 18.013\n   0.812 12.499\n   0.832 7.107\n   0.849 3.676\n   0.87 1.225\n   0.898 0.368\n   0.92 0.0\n",
    "source": {
      "file": "AeroTech_F67W.eng",
      "motorId": "5f4294d2000231000000045a",
      "simfileId": "5f4294d20002e9000000088a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000088a/",
      "designation": "F67W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Aerotech G40W RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case G40W motors.\nG40W 29 124 4-7-10 0.0538 0.123 AeroTech\n0.024 74.325\n0.057 67.005\n0.252 65.879\n0.5 63.063\n0.765 60.248\n1 54.054\n1.25 47.298\n1.502 36.599\n1.751 25.338\n1.999 12.951\n2.121 3.941\n2.3 0\n",
    "source": {
      "file": "AeroTech_G40W.eng",
      "motorId": "5f4294d20002310000000059",
      "simfileId": "5f4294d20002e90000000463",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000463/",
      "designation": "G40W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; Aerotech G64 Bifurcated RASP.ENG file made from data Supplied by Aerotech \r\n; File produced August 10 by Tim Barr\r\n; The curve drawn with these data points is as\r\n; close to the test curve as can be with such a limited\r\n; number of points (32) allowed with wRASP up to v1.6.\r\nG64BF 29 124 4-8-10 0.0625 0.1512 AERO\r\n0.01\t9.5637\r\n0.02\t60.0510\r\n0.03\t77.4880\r\n0.04\t90.3211\r\n0.05\t98.8061\r\n0.06\t102.9986\r\n0.07\t105.9789\r\n0.08\t108.1140\r\n0.09\t108.0695\r\n0.10\t106.4237\r\n0.15\t104.0773\r\n0.25\t103.3222\r\n0.35\t100.4053\r\n0.45\t95.4399\r\n0.55\t90.4957\r\n0.65\t85.0522\r\n0.75\t79.2640\r\n0.95\t67.6591\r\n1.15\t53.0840\r\n1.35\t38.1535\r\n1.55\t23.7201\r\n1.75\t11.4636\r\n1.95\t4.6295\r\n2.15\t1.4518\r\n2.35\t0.1101\r\n2.44\t0",
    "source": {
      "file": "AeroTech_G64.eng",
      "motorId": "5f4294d20002310000000060",
      "simfileId": "5f4294d20002e9000000081a",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000081a/",
      "designation": "G64BF",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; G74W Economax\nG74W 29 83 4-6-9 0.039299999999999995 0.08700000000000001 AT\n   0.023 6.551\n   0.05 21.838\n   0.088 44.852\n   0.124 67.362\n   0.135 71.561\n   0.148 74.417\n   0.197 80.128\n   0.248 85.0\n   0.298 87.52\n   0.397 89.704\n   0.499 91.215\n   0.6 90.375\n   0.699 90.375\n   0.751 89.536\n   0.8 87.856\n   0.9 84.496\n   0.954 82.144\n   0.971 81.808\n   0.987 79.96\n   1.002 76.433\n   1.023 67.194\n   1.065 44.516\n   1.094 22.174\n   1.107 15.287\n   1.126 6.887\n   1.138 3.36\n   1.157 1.344\n   1.18 0.168\n   1.192 0.0\n",
    "source": {
      "file": "AeroTech_G74W.eng",
      "motorId": "5f4294d20002310000000400",
      "simfileId": "5f4294d20002e900000007f0",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007f0/",
      "designation": "G74W",
      "manufacturer": "AeroTech",
      "commonName": "G74"
    }
  },
  {
    "eng": ";\n; Aerotech G77R (Redline)\n;\n; AeroTech RMS-29/120 EZ Access Reloadable Motors (New! Hardware).\n; New AeroTech Redline Motor. Just announced on AeroTech's Website!\n; File produced 28 Feb 2005.\n;\n; The file was produced by scaling data points off the\n; thrust curve in the manufacturers catalog sheet.\n;\n; The motor is not yet on www.thrustcurve.org.\n; Hence the amateur file production.\n; The file was created by Stan Hemphill.\n; Contact at stanley_hemphill@hotmail.com.\n;\n; Motor Dia  Len  Delay Prop Gross Mfg\nG77R 29 150 4-6-8-9-10-12-13-15-17 0.0554 0.155 AT\n0.0132 014.8333\n0.0243 032.4479\n0.0331 046.3542\n0.0375 052.8438\n0.0463 056.5521\n0.0617 059.3333\n0.2580 073.2396\n0.6548 087.1458\n0.8709 089.0000\n0.8885 085.2917\n1.0252 086.2188\n1.0472 084.3646\n1.0715 086.2188\n1.1002 084.3646\n1.1332 085.2917\n1.1950 076.9479\n1.2104 076.0208\n1.2369 065.8229\n1.2611 043.5729\n1.2898 027.8125\n1.3317 012.0521\n1.3625 004.6354\n1.4000 000.0000",
    "source": {
      "file": "AeroTech_G77R.eng",
      "motorId": "5f4294d20002310000000065",
      "simfileId": "5f4294d20002e90000000120",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000120/",
      "designation": "G77R",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";G80 New Blue Thunder\nG80NBT 29 123.825 4-7-10 0.069 0.129 AT \n0.013 89.054\n0.018 101.584\n0.029 105.388\n0.047 102.927\n0.104 100.018\n0.19 102.255\n0.268 104.94\n0.306 104.269\n0.352 105.835\n0.41 104.94\n0.432 106.73\n0.512 105.612\n0.563 106.954\n0.591 104.493\n0.62 106.283\n0.715 103.15\n0.76 103.374\n0.806 101.36\n0.848 102.032\n1.2 88.383\n1.243 77.866\n1.269 57.952\n1.302 44.079\n1.329 34.011\n1.367 26.403\n1.398 22.823\n1.433 20.585\n1.48 21.704\n1.508 20.809\n1.584 13.201\n1.604 11.635\n1.652 11.188\n1.683 5.37\n1.701 0\n;\n",
    "source": {
      "file": "AeroTech_G80T.eng",
      "motorId": "5f4294d20002310000000068",
      "simfileId": "5f4294d20002e900000007dd",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007dd/",
      "designation": "G80T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; H100W DMS\r\nH100W 38 157.5 14 0.121 0.261 AT\r\n   0.004 46.916\r\n   0.031 66.29\r\n   0.047 97.334\r\n   0.096 109.005\r\n   0.193 116.474\r\n   0.302 124.877\r\n   0.391 123.01\r\n   0.498 127.911\r\n   0.604 128.845\r\n   0.696 130.245\r\n   0.798 128.612\r\n   0.902 128.845\r\n   0.998 127.445\r\n   1.098 126.511\r\n   1.2 116.941\r\n   1.3 114.607\r\n   1.4 110.172\r\n   1.5 98.268\r\n   1.6 90.798\r\n   1.7 80.061\r\n   1.802 68.624\r\n   1.9 65.356\r\n   2.0 56.953\r\n   2.1 49.484\r\n   2.202 25.209\r\n   2.298 5.135\r\n   2.398 0.0",
    "source": {
      "file": "AeroTech_H100W.eng",
      "motorId": "5f4294d20002310000000440",
      "simfileId": "5f4294d20002e90000000854",
      "license": "free",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000854/",
      "designation": "H100W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech H128W\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH128W 29 194 14 0.09408 0.2016 AT\n   0.024 102.423\n   0.074 175.203\n   0.125 181.379\n   0.176 179.281\n   0.226 181.423\n   0.277 186.074\n   0.328 190.483\n   0.378 189.509\n   0.429 186.162\n   0.480 184.114\n   0.530 180.300\n   0.581 174.144\n   0.632 172.019\n   0.683 169.360\n   0.734 166.017\n   0.784 161.882\n   0.835 157.331\n   0.886 153.073\n   0.936 151.985\n   0.988 139.902\n   1.039 87.865\n   1.089 40.857\n   1.140 14.328\n   1.191 4.330\n   1.242 1.550\n   1.293 0.000\n",
    "source": {
      "file": "AeroTech_H128W.eng",
      "motorId": "5f4294d20002310000000083",
      "simfileId": "5f4294d20002e9000000000d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000d/",
      "designation": "H128W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech H148R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH148R 38 152 0 0.14784 0.30912 AT\n   0.027 77.232\n   0.088 174.296\n   0.148 185.046\n   0.208 190.458\n   0.268 192.497\n   0.327 191.996\n   0.388 188.790\n   0.448 187.548\n   0.509 182.697\n   0.570 178.151\n   0.630 172.906\n   0.690 169.607\n   0.750 164.510\n   0.810 158.375\n   0.870 153.019\n   0.930 146.810\n   0.991 139.443\n   1.053 132.001\n   1.112 123.271\n   1.173 112.559\n   1.233 104.737\n   1.292 97.657\n   1.353 94.932\n   1.413 60.644\n   1.474 13.007\n   1.535 0.000\n",
    "source": {
      "file": "AeroTech_H148R.eng",
      "motorId": "5f4294d20002310000000087",
      "simfileId": "5f4294d20002e9000000000f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000f/",
      "designation": "H148R",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech H180W\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH180W 29 238 6 0.12096 0.2464 AT\n   0.024 149.374\n   0.075 222.273\n   0.127 222.339\n   0.178 227.835\n   0.229 234.963\n   0.281 238.162\n   0.333 240.252\n   0.384 243.126\n   0.435 240.757\n   0.487 240.724\n   0.539 236.311\n   0.590 236.799\n   0.642 234.897\n   0.694 232.763\n   0.745 229.198\n   0.796 228.816\n   0.848 231.906\n   0.899 225.853\n   0.950 188.285\n   1.002 134.679\n   1.054 78.940\n   1.105 34.557\n   1.156 15.482\n   1.208 7.279\n   1.260 3.585\n   1.313 0.000",
    "source": {
      "file": "AeroTech_H180W.eng",
      "motorId": "5f4294d2000231000000008b",
      "simfileId": "5f4294d20002e90000000013",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000013/",
      "designation": "H180W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech H242T\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH242T 38 152 10 0.11648 0.2688 AT\n   0.030 164.060\n   0.093 197.516\n   0.155 204.324\n   0.218 208.970\n   0.280 211.481\n   0.343 211.261\n   0.405 209.291\n   0.468 208.438\n   0.531 206.707\n   0.595 203.967\n   0.657 198.175\n   0.720 192.137\n   0.782 186.840\n   0.845 180.802\n   0.907 174.635\n   0.970 165.581\n   1.033 159.726\n   1.097 151.690\n   1.159 144.167\n   1.222 138.550\n   1.284 119.114\n   1.347 69.055\n   1.409 21.396\n   1.472 3.473\n   1.535 0.594\n   1.599 0.000\n",
    "source": {
      "file": "AeroTech_H242T.eng",
      "motorId": "5f4294d20002310000000091",
      "simfileId": "5f4294d20002e90000000019",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000019/",
      "designation": "H242T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; 38mm DMS Super Thunder\nH283ST 38 155 7-11-15 0.097 0.247 AT\n   0.003 133.038\n   0.005 223.16\n   0.007 267.302\n   0.009 285.694\n   0.017 296.73\n   0.045 300.408\n   0.049 310.83\n   0.052 301.634\n   0.066 304.7\n   0.081 312.67\n   0.094 308.378\n   0.108 315.122\n   0.222 331.062\n   0.225 337.193\n   0.229 332.901\n   0.336 316.348\n   0.371 312.67\n   0.404 300.408\n   0.435 289.986\n   0.449 290.599\n   0.47 278.337\n   0.499 274.046\n   0.538 257.493\n   0.572 239.1\n   0.593 239.713\n   0.606 226.839\n   0.636 225.613\n   0.644 221.934\n   0.658 178.406\n   0.67 129.972\n   0.677 121.389\n   0.688 91.962\n   0.691 98.092\n   0.722 41.689\n   0.738 23.297\n   0.74 0.0\n",
    "source": {
      "file": "AeroTech_H283ST.eng",
      "motorId": "5f4294d20002310000000455",
      "simfileId": "5f4294d20002e90000000872",
      "license": "free",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000872/",
      "designation": "H283ST-15A",
      "manufacturer": "AeroTech",
      "commonName": "H283"
    }
  },
  {
    "eng": "; AT H550 ST RMS\nH550 38 213 14 0.176 0.323 AT\n   0.008 445.411\n   0.009 533.786\n   0.01 565.601\n   0.013 586.812\n   0.015 623.34\n   0.021 639.837\n   0.036 606.843\n   0.045 629.232\n   0.057 615.092\n   0.061 635.123\n   0.067 619.805\n   0.101 637.48\n   0.116 622.162\n   0.157 643.372\n   0.174 623.34\n   0.196 623.34\n   0.205 639.837\n   0.231 631.588\n   0.234 618.627\n   0.255 611.557\n   0.268 628.053\n   0.314 595.06\n   0.334 600.952\n   0.362 571.493\n   0.386 565.601\n   0.401 556.175\n   0.426 518.468\n   0.445 503.15\n   0.493 447.768\n   0.505 447.768\n   0.511 456.016\n   0.519 451.303\n   0.535 357.036\n   0.545 266.304\n   0.551 179.107\n   0.559 91.91\n   0.565 42.42\n   0.572 12.962\n   0.579 0.0\n",
    "source": {
      "file": "AeroTech_H550ST.eng",
      "motorId": "5f4294d20002310000000456",
      "simfileId": "5f4294d20002e90000000873",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000873/",
      "designation": "H550ST",
      "manufacturer": "AeroTech",
      "commonName": "H550"
    }
  },
  {
    "eng": ";\n; 38-240\n;  Greg Gardner - 09/15/06\nH669N  38 152  0  0.096  0.252  AT\n0.003  141\n0.006  523\n0.009  934\n0.012  1178\n0.016  926\n0.019  684\n0.022  487\n0.025  415\n0.028  622\n0.031  801\n0.0325  906\n0.034  866\n0.037  755\n0.04   737\n0.043  666\n0.047  737\n0.0485  802\n0.05   755\n0.053  791\n0.056  765\n0.059  755\n0.062  747\n0.069  737\n0.075  761\n0.082  755\n0.088  729\n0.093  741\n0.1    751\n0.2    703\n0.25   640\n0.3    586\n0.306  584\n0.309  576\n0.312  506\n0.318  292\n0.325  93\n0.329  0\n;\n",
    "source": {
      "file": "AeroTech_H669N.eng",
      "motorId": "5f4294d2000231000000009b",
      "simfileId": "5f4294d20002e9000000026a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000026a/",
      "designation": "H669N",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\r\n; 38-360\r\n;  Greg Gardner - 09/15/06\r\nH999N 38 203 0 0.144 0.331 AT\r\n0.003  204\r\n0.006  757\r\n0.009  1357\r\n0.012  1710\r\n0.016  1345\r\n0.019  995\r\n0.022  710\r\n0.025  606\r\n0.028  905\r\n0.031  1165\r\n0.0325  1311\r\n0.034  1258\r\n0.037  1098\r\n0.04   1072\r\n0.043  969\r\n0.047  1072\r\n0.0485  1166\r\n0.05   1098\r\n0.053  1160\r\n0.056  1117\r\n0.059  1103\r\n0.062  1093\r\n0.069  1076\r\n0.075  1110\r\n0.082  1105\r\n0.088  1065\r\n0.093  1082\r\n0.1    1092\r\n0.2    1022\r\n0.25   931\r\n0.3    853\r\n0.306  850\r\n0.309  838\r\n0.312  735\r\n0.318  435\r\n0.325  161\r\n0.329  0\r\n;\n",
    "source": {
      "file": "AeroTech_H999N.eng",
      "motorId": "5f4294d2000231000000009c",
      "simfileId": "5f4294d20002e9000000026b",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000026b/",
      "designation": "H999N",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech Pro-SU 29mm H135 14sec adjustable delay.\n; From Tripoli Data Sheet updated 2013/02/10\n; Created by Robert Belknap 2013/03/04\nH135W 29 216 6-8-10-12-14 0.082 0.212 AT\n   0.014 159.806\n   0.045 110.931\n   0.104 144.43\n   0.131 135.643\n   0.252 154.315\n   0.293 130.701\n   0.387 149.921\n   1.005 140.037\n   1.261 119.168\n   1.297 142.233\n   1.324 109.833\n   1.387 120.267\n   1.518 110.382\n   1.595 80.727\n   1.685 60.408\n   1.797 33.499\n   1.896 14.278\n   2.072 0.0\n",
    "source": {
      "file": "AeroTech_HP-H135W.eng",
      "motorId": "5f4294d200023100000003f1",
      "simfileId": "5f4294d20002e900000007d7",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007d7/",
      "designation": "HP-H135W",
      "manufacturer": "AeroTech",
      "commonName": "H135"
    }
  },
  {
    "eng": "; Aerotech I115W from TRA Cert Data\nI115W 54 156 6-10-14-P 0.229 0.58 AT\n   0.034 12.095\n   0.177 105.225\n   0.206 113.087\n   1.017 163.281\n   1.166 161.466\n   1.257 162.676\n   1.343 166.909\n   1.417 160.862\n   1.514 162.676\n   1.617 163.885\n   1.686 160.257\n   1.977 142.719\n   2.497 106.435\n   2.68 91.316\n   2.994 72.569\n   3.103 67.126\n   3.189 65.917\n   3.24 59.265\n   3.291 42.937\n   3.331 30.237\n   3.377 20.561\n   3.429 12.7\n   3.491 7.257\n   3.514 0.0\n",
    "source": {
      "file": "AeroTech_I115W.eng",
      "motorId": "5f4294d200023100000001e7",
      "simfileId": "5f4294d20002e90000000423",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000423/",
      "designation": "I115W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";Entered by Jim Yehle\n;from TRA cert document\nI1299N 38 249 1000 0.192 0.422 AT-RMS \n0 15.7171\n0.00361 222.5\n0.0115 1112\n0.0134228 1237.11\n0.02 1287\n0.04 1359\n0.1 1451\n0.12 1470\n0.18 1491\n0.2 1483\n0.22 1462\n0.24 1399\n0.28 1208\n0.294743 1131.63\n0.3 1065\n0.304251 974.46\n0.32 305\n0.330537 55.0098\n0.333893 11.7878\n0.34 0\n;\n",
    "source": {
      "file": "AeroTech_I1299N.eng",
      "motorId": "5f4294d200023100000001c5",
      "simfileId": "5f4294d20002e90000000273",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000273/",
      "designation": "I1299N",
      "manufacturer": "AeroTech",
      "commonName": "I1299"
    }
  },
  {
    "eng": "; AeroTech I161W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI161W 38 191 0 0.189952 0.370048 AT\n   0.043 178.900\n   0.131 206.770\n   0.221 206.101\n   0.310 205.175\n   0.400 206.924\n   0.490 210.603\n   0.579 210.475\n   0.669 211.555\n   0.758 212.379\n   0.848 212.096\n   0.938 209.060\n   1.027 202.345\n   1.116 192.439\n   1.204 179.499\n   1.294 162.159\n   1.383 148.446\n   1.473 135.222\n   1.563 120.095\n   1.652 104.041\n   1.742 87.962\n   1.831 74.789\n   1.921 54.362\n   2.010 23.386\n   2.100 7.332\n   2.190 5.171\n   2.279 0.000\n",
    "source": {
      "file": "AeroTech_I161W.eng",
      "motorId": "5f4294d200023100000000b1",
      "simfileId": "5f4294d20002e9000000002d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000002d/",
      "designation": "I161W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech I200W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI200W 29 333 0 0.181888 0.357504 AT\n   0.033 303.951\n   0.103 273.452\n   0.174 276.061\n   0.245 271.625\n   0.316 268.233\n   0.386 258.449\n   0.457 252.480\n   0.528 246.642\n   0.599 242.304\n   0.670 237.737\n   0.741 234.769\n   0.811 233.171\n   0.882 230.660\n   0.953 224.985\n   1.024 221.658\n   1.095 214.548\n   1.166 177.365\n   1.236 154.208\n   1.307 119.146\n   1.378 91.586\n   1.449 65.330\n   1.520 32.877\n   1.591 28.702\n   1.661 22.211\n   1.732 15.558\n   1.803 0.000",
    "source": {
      "file": "AeroTech_I200W.eng",
      "motorId": "5f4294d200023100000000b5",
      "simfileId": "5f4294d20002e90000000033",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000033/",
      "designation": "I200W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech I211W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI211W 38 240 0 0.247296 0.466368 AT\n   0.044 257.326\n   0.134 295.533\n   0.226 296.087\n   0.318 298.204\n   0.408 295.082\n   0.499 287.669\n   0.591 282.578\n   0.682 272.875\n   0.773 266.997\n   0.864 257.602\n   0.955 250.495\n   1.047 238.574\n   1.138 228.571\n   1.228 215.135\n   1.320 198.047\n   1.411 180.631\n   1.502 161.261\n   1.593 146.708\n   1.684 134.484\n   1.776 101.241\n   1.867 52.688\n   1.957 35.461\n   2.049 24.321\n   2.141 11.165\n   2.232 4.587\n   2.324 0.000\n",
    "source": {
      "file": "AeroTech_I211W.eng",
      "motorId": "5f4294d200023100000000b9",
      "simfileId": "5f4294d20002e90000000035",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000035/",
      "designation": "I211W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech I284W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI284W 38 297 0 0.310016 0.555072 AT\n   0.041 422.031\n   0.125 448.597\n   0.210 459.029\n   0.295 451.940\n   0.379 439.556\n   0.465 427.370\n   0.549 407.558\n   0.633 399.734\n   0.719 380.049\n   0.803 368.042\n   0.887 352.020\n   0.973 342.102\n   1.057 325.767\n   1.142 306.936\n   1.227 292.029\n   1.311 267.283\n   1.396 251.784\n   1.481 227.534\n   1.566 210.504\n   1.650 168.299\n   1.735 110.789\n   1.820 71.036\n   1.904 32.505\n   1.990 17.537\n   2.075 7.317\n   2.160 0.000",
    "source": {
      "file": "AeroTech_I284W.eng",
      "motorId": "5f4294d200023100000000c5",
      "simfileId": "5f4294d20002e9000000003b",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000003b/",
      "designation": "I284W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nI300T 38 250 6-10-14 0.2216 0.4405 AT\n0 473.17\n0.1 395.68\n0.2 375.31\n0.3 367.14\n0.4 358.97\n0.5 346.72\n0.6 338.56\n0.7 318.19\n0.8 305.94\n0.9 295.35\n1.07 269.23\n1.1 258.01\n1.2 246.79\n1.3 179.49\n1.4 48.95\n1.5 13.91\n1.6 0\n",
    "source": {
      "file": "AeroTech_I300T.eng",
      "motorId": "5f4294d200023100000000cb",
      "simfileId": "5f4294d20002e9000000046a",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000046a/",
      "designation": "I300T",
      "manufacturer": "AeroTech",
      "commonName": "I300"
    }
  },
  {
    "eng": "; AeroTech I357T\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI357T 38 203 14 0.1792 0.34944 AT\n   0.028 311.629\n   0.087 351.768\n   0.147 349.074\n   0.206 346.175\n   0.266 341.229\n   0.325 336.857\n   0.384 333.748\n   0.444 326.960\n   0.503 319.679\n   0.563 312.533\n   0.622 300.790\n   0.681 292.787\n   0.741 283.766\n   0.800 274.578\n   0.859 264.915\n   0.919 254.273\n   0.978 241.755\n   1.037 229.020\n   1.097 216.238\n   1.156 187.776\n   1.216 109.940\n   1.275 56.459\n   1.334 24.476\n   1.394 10.977\n   1.454 3.450\n   1.515 0.000\n",
    "source": {
      "file": "AeroTech_I357T.eng",
      "motorId": "5f4294d200023100000000d3",
      "simfileId": "5f4294d20002e9000000003f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000003f/",
      "designation": "I357T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; Aerotech I59WN-P\nI59WN-P 38 232 P 0.272 0.487 AT\n   0.0090 0.357\n   0.046 138.571\n   0.12 150.0\n   0.193 147.857\n   0.368 157.857\n   0.506 167.857\n   0.699 171.071\n   0.791 171.786\n   0.893 168.571\n   1.058 158.214\n   1.233 146.429\n   1.417 132.143\n   1.509 125.714\n   1.61 100.357\n   1.675 80.357\n   1.785 60.357\n   1.96 53.571\n   2.209 48.571\n   2.531 45.357\n   2.669 43.214\n   3.009 40.714\n   3.387 40.714\n   4.021 38.929\n   4.261 37.5\n   4.997 36.429\n   6.0 33.929\n   6.883 31.429\n   7.003 33.571\n   7.187 30.714\n   7.334 27.5\n   7.574 22.5\n   7.96 17.5\n   8.117 9.643\n   8.319 4.643\n   8.604 0.0\n",
    "source": {
      "file": "AeroTech_I59WN.eng",
      "motorId": "5f4294d200023100000002d0",
      "simfileId": "5f4294d20002e90000000660",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000660/",
      "designation": "I59WN",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech J315R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ315R 54 243 0 0.42112 0.8512 AT\n   0.051 189.719\n   0.154 337.529\n   0.259 354.534\n   0.363 364.111\n   0.468 371.479\n   0.572 373.222\n   0.676 376.062\n   0.780 372.962\n   0.884 368.988\n   0.989 366.978\n   1.093 358.752\n   1.197 351.302\n   1.301 339.336\n   1.406 325.202\n   1.510 311.322\n   1.614 300.496\n   1.718 288.598\n   1.822 278.279\n   1.927 270.538\n   2.031 262.127\n   2.136 245.027\n   2.239 236.238\n   2.344 188.308\n   2.448 63.668\n   2.552 18.746\n   2.657 0.000\n",
    "source": {
      "file": "AeroTech_J315R.eng",
      "motorId": "5f4294d20002310000000106",
      "simfileId": "5f4294d20002e90000000053",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000053/",
      "designation": "J315R",
      "manufacturer": "AeroTech",
      "commonName": "J315"
    }
  },
  {
    "eng": "; AeroTech J350W\r\n; converted from TMT test stand data 1998 (www.tripoli.org)\r\n; provided by ThrustCurve.org (www.thrustcurve.org)\r\nJ350W 38 337 0 0.375872 0.650944 AT\r\n   0.038 706.781\r\n   0.115 669.055\r\n   0.192 602.539\r\n   0.270 565.084\r\n   0.348 539.143\r\n   0.425 514.910\r\n   0.503 483.098\r\n   0.581 449.128\r\n   0.658 437.256\r\n   0.736 424.199\r\n   0.815 414.461\r\n   0.892 402.956\r\n   0.970 393.604\r\n   1.048 377.837\r\n   1.125 359.785\r\n   1.203 341.916\r\n   1.281 324.721\r\n   1.358 305.935\r\n   1.436 264.279\r\n   1.515 175.471\r\n   1.592 110.912\r\n   1.670 77.100\r\n   1.748 55.472\r\n   1.825 39.990\r\n   1.903 26.276\r\n   1.981 0.000\r\n;",
    "source": {
      "file": "AeroTech_J350W.eng",
      "motorId": "5f4294d2000231000000010e",
      "simfileId": "5f4294d20002e900000002a7",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000002a7/",
      "designation": "J350W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech J420R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ420R 38 337 0 0.37632 0.6496 AT\n   0.031 61.083\n   0.095 563.470\n   0.160 525.283\n   0.224 521.242\n   0.288 527.371\n   0.352 537.088\n   0.418 535.138\n   0.481 534.623\n   0.545 530.245\n   0.610 526.447\n   0.674 517.203\n   0.738 510.279\n   0.802 500.887\n   0.868 479.450\n   0.931 460.675\n   0.995 438.594\n   1.060 409.647\n   1.124 383.454\n   1.188 361.024\n   1.252 339.741\n   1.318 319.194\n   1.381 296.714\n   1.445 195.191\n   1.510 61.984\n   1.575 7.220\n   1.640 0.000\n",
    "source": {
      "file": "AeroTech_J420R.eng",
      "motorId": "5f4294d2000231000000011c",
      "simfileId": "5f4294d20002e90000000057",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000057/",
      "designation": "J420R",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";Delays are speculation.\r\n;Taken from Aerotech curves, not cert docs.\r\n;Jim Yehle 15 Nov 07\r\nJ500G 38 335.407 0-6-10-14 0.3626 0.654 Aerotech \r\n0.0134378 40.2458\r\n0.0335946 724.425\r\n0.0403135 781.616\r\n0.0604703 787.971\r\n0.0895857 711.716\r\n0.134378 686.297\r\n0.394177 637.578\r\n0.575588 588.86\r\n0.606943 622.751\r\n0.633819 620.633\r\n1.20045 360.094\r\n1.24076 345.267\r\n1.31019 182.165\r\n1.38186 65.6642\r\n1.43337 23.3002\r\n1.45 0\r\n;",
    "source": {
      "file": "AeroTech_J500G.eng",
      "motorId": "5f4294d200023100000001e5",
      "simfileId": "5f4294d20002e9000000029e",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000029e/",
      "designation": "J500G",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech J570W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ570W 38 479 0 0.547904 0.886144 AT\n   0.039 1149.795\n   0.119 1042.846\n   0.199 960.891\n   0.279 900.020\n   0.360 837.772\n   0.441 792.834\n   0.521 735.510\n   0.602 685.857\n   0.682 649.599\n   0.762 608.757\n   0.844 597.350\n   0.924 568.934\n   1.004 548.552\n   1.084 505.080\n   1.165 484.626\n   1.246 452.328\n   1.326 362.439\n   1.406 297.973\n   1.487 262.381\n   1.568 195.696\n   1.648 156.733\n   1.729 124.649\n   1.809 113.749\n   1.890 69.812\n   1.971 46.023\n   2.052 0.000\n",
    "source": {
      "file": "AeroTech_J570W.eng",
      "motorId": "5f4294d20002310000000126",
      "simfileId": "5f4294d20002e9000000005d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000005d/",
      "designation": "J570W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech J800T\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ800T 54 314 0 0.613312 1.08595 AT\n   0.040 841.341\n   0.121 818.497\n   0.203 776.386\n   0.285 784.308\n   0.367 785.314\n   0.449 783.315\n   0.531 782.539\n   0.612 779.977\n   0.695 773.680\n   0.777 765.307\n   0.858 755.517\n   0.941 744.777\n   1.023 733.131\n   1.105 719.947\n   1.187 702.235\n   1.269 685.369\n   1.351 668.265\n   1.433 650.327\n   1.515 630.472\n   1.597 615.483\n   1.679 470.262\n   1.760 256.617\n   1.843 108.716\n   1.925 15.005\n   2.007 1.249\n   2.090 0.000",
    "source": {
      "file": "AeroTech_J800T.eng",
      "motorId": "5f4294d20002310000000129",
      "simfileId": "5f4294d20002e9000000005f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000005f/",
      "designation": "J800T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech J90W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ90W 54 243 0 0.427392 0.852544 AT\n   0.143 116.187\n   0.430 165.444\n   0.718 176.536\n   1.005 184.645\n   1.293 187.242\n   1.580 183.651\n   1.868 175.492\n   2.155 167.687\n   2.443 156.858\n   2.730 143.514\n   3.018 128.856\n   3.305 110.879\n   3.593 94.003\n   3.880 79.657\n   4.168 67.472\n   4.455 57.268\n   4.743 48.008\n   5.030 40.523\n   5.318 33.901\n   5.605 28.248\n   5.893 23.334\n   6.180 19.275\n   6.468 15.923\n   6.755 12.727\n   7.044 9.903\n   7.332 0.000\n",
    "source": {
      "file": "AeroTech_J90W.eng",
      "motorId": "5f4294d200023100000000df",
      "simfileId": "5f4294d20002e90000000061",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000061/",
      "designation": "J90W",
      "manufacturer": "AeroTech",
      "commonName": "J90"
    }
  },
  {
    "eng": "K1050W 54 635 1000 1.373 2.259 Aerotech \r\n0 934.5\r\n0.05 1468.5\r\n0.1 1335\r\n0.15 1290.5\r\n0.25 1246\r\n0.75 1246\r\n1.25 1201.5\r\n1.5 1157\r\n1.65 1157\r\n1.75 1246\r\n1.9 890\r\n2.1 578.5\r\n2.2 222.5\r\n2.46 0",
    "source": {
      "file": "AeroTech_K1050W.eng",
      "motorId": "5f4294d2000231000000024e",
      "simfileId": "5f4294d20002e90000000564",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000564/",
      "designation": "K1050W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech K1275R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK1275R 54 569 0 1.29024 2.03392 AT\n   0.039 1282.616\n   0.119 1557.989\n   0.199 1540.196\n   0.279 1526.782\n   0.359 1500.693\n   0.440 1456.584\n   0.520 1425.794\n   0.600 1390.416\n   0.680 1355.109\n   0.761 1323.311\n   0.841 1282.825\n   0.921 1247.795\n   1.001 1194.417\n   1.081 1150.977\n   1.162 1108.223\n   1.242 1068.754\n   1.322 1036.922\n   1.403 997.444\n   1.482 964.569\n   1.563 933.305\n   1.644 889.992\n   1.724 599.467\n   1.804 134.559\n   1.884 5.630\n   1.964 0.205\n   2.045 0.000\n",
    "source": {
      "file": "AeroTech_K1275R.eng",
      "motorId": "5f4294d20002310000000167",
      "simfileId": "5f4294d20002e90000000067",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000067/",
      "designation": "K1275R",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech K250W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK250W 54 673 0 1.52902 2.21133 AT\n   0.199 365.330\n   0.599 403.324\n   0.999 418.669\n   1.400 409.813\n   1.801 408.949\n   2.201 412.146\n   2.602 411.952\n   3.003 409.488\n   3.403 393.214\n   3.804 373.599\n   4.205 348.913\n   4.605 328.463\n   5.006 307.163\n   5.407 281.467\n   5.807 249.011\n   6.208 217.159\n   6.609 185.908\n   7.009 149.190\n   7.410 119.808\n   7.811 92.096\n   8.211 69.726\n   8.613 52.613\n   9.014 35.876\n   9.414 16.727\n   9.815 4.086\n   10.216 0.000",
    "source": {
      "file": "AeroTech_K250W.eng",
      "motorId": "5f4294d20002310000000132",
      "simfileId": "5f4294d20002e9000000006b",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000006b/",
      "designation": "K250W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech K550W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK550W 54 410 0 0.919744 1.48736 AT\n   0.065 604.264\n   0.196 642.625\n   0.327 682.197\n   0.458 732.995\n   0.591 758.236\n   0.723 780.289\n   0.854 794.452\n   0.985 797.939\n   1.117 797.601\n   1.249 773.842\n   1.381 711.608\n   1.512 646.522\n   1.644 590.724\n   1.775 537.505\n   1.907 491.012\n   2.040 445.836\n   2.171 401.461\n   2.302 364.291\n   2.433 319.614\n   2.566 255.577\n   2.698 172.573\n   2.829 103.501\n   2.960 51.795\n   3.092 26.814\n   3.224 15.203\n   3.356 0.000\n",
    "source": {
      "file": "AeroTech_K550W.eng",
      "motorId": "5f4294d20002310000000146",
      "simfileId": "5f4294d20002e90000000071",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000071/",
      "designation": "K550W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech K700W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK700W 54 568 0 1.29158 2.03526 AT\n   0.069 1005.472\n   0.209 1018.916\n   0.350 1026.610\n   0.491 1028.637\n   0.632 1029.337\n   0.773 1004.203\n   0.914 970.694\n   1.055 946.516\n   1.196 918.437\n   1.336 873.783\n   1.478 821.276\n   1.619 773.270\n   1.759 735.553\n   1.900 692.732\n   2.041 658.984\n   2.182 626.737\n   2.323 591.431\n   2.464 508.666\n   2.605 420.175\n   2.746 328.309\n   2.886 202.409\n   3.028 121.672\n   3.169 80.453\n   3.309 50.873\n   3.451 31.548\n   3.593 0.000",
    "source": {
      "file": "AeroTech_K700W.eng",
      "motorId": "5f4294d2000231000000015a",
      "simfileId": "5f4294d20002e90000000079",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000079/",
      "designation": "K700W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; per AT announcement 5/8/14\r\nL1000 54 635 18 1.4000000000000001 2.194 AT\r\n   0.004 10.664\r\n   0.011 1268.961\r\n   0.04 1322.279\r\n   0.195 1226.307\r\n   0.249 1268.961\r\n   0.296 1242.303\r\n   0.372 1252.966\r\n   0.416 1215.644\r\n   0.6 1226.307\r\n   0.788 1215.644\r\n   1.066 1183.653\r\n   1.261 1167.658\r\n   1.507 1125.004\r\n   1.746 1087.681\r\n   1.865 1050.359\r\n   1.995 1045.027\r\n   2.093 911.733\r\n   2.158 746.448\r\n   2.263 554.504\r\n   2.389 405.215\r\n   2.577 191.944\r\n   2.693 85.308\r\n   2.761 42.654\r\n   3.0 0.0",
    "source": {
      "file": "AeroTech_L1000.eng",
      "motorId": "5f4294d2000231000000040b",
      "simfileId": "5f4294d20002e900000007f6",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007f6/",
      "designation": "L1000",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech L1150\n; provided by ThrustCurve.org (www.thrustcurve.org)\nL1150 75 531 0 2.06528 3.6736 AT\n   0.053 935.855\n   0.175 1292.642\n   0.300 1260.926\n   0.425 1241.482\n   0.550 1257.058\n   0.675 1272.287\n   0.800 1287.605\n   0.925 1301.012\n   1.048 1309.708\n   1.170 1308.417\n   1.295 1304.830\n   1.420 1285.265\n   1.545 1267.657\n   1.670 1255.624\n   1.795 1227.212\n   1.920 1202.443\n   2.043 1182.617\n   2.165 1150.712\n   2.290 1117.909\n   2.415 1081.739\n   2.540 1037.547\n   2.665 1007.091\n   2.790 1008.911\n   2.915 643.124\n   3.040 64.371\n   3.165 0.000\n",
    "source": {
      "file": "AeroTech_L1150R.eng",
      "motorId": "5f4294d2000231000000018f",
      "simfileId": "5f4294d20002e9000000007f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000007f/",
      "designation": "L1150R",
      "manufacturer": "AeroTech",
      "commonName": "L1150"
    }
  },
  {
    "eng": "; from TMT document and posted thrust curve\nL1940X 75 560.4 P 1.8234317999999998 3.855515 AT\n   0.02 48.137\n   0.04 2107.333\n   0.055 2289.184\n   0.073 2150.122\n   0.156 2101.985\n   0.397 2150.122\n   0.691 2155.47\n   0.982 2118.03\n   1.41 2000.362\n   1.696 1898.739\n   1.935 1839.905\n   2.06 1818.511\n   2.103 1652.705\n   2.116 1374.58\n   2.133 935.998\n   2.163 534.856\n   2.214 240.685\n   2.244 112.32\n   2.296 5.349\n   2.309 0.0\n",
    "source": {
      "file": "AeroTech_L1940X.eng",
      "motorId": "60ac748b8dc4640004c24d85",
      "simfileId": "60ac84458dc4640004c24eb6",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/60ac84458dc4640004c24eb6/",
      "designation": "L1940X",
      "manufacturer": "AeroTech",
      "commonName": "L1940"
    }
  },
  {
    "eng": "; AeroTech L850W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nL850W 75 531 0 2.06528 3.67315 AT\n   0.091 1015.926\n   0.274 1064.942\n   0.458 1101.366\n   0.643 1143.358\n   0.827 1170.928\n   1.011 1184.795\n   1.196 1178.044\n   1.380 1177.598\n   1.564 1174.910\n   1.748 1170.021\n   1.932 1113.716\n   2.117 1042.586\n   2.301 972.795\n   2.485 908.071\n   2.670 844.471\n   2.854 773.595\n   3.039 714.046\n   3.222 649.095\n   3.406 597.341\n   3.591 557.444\n   3.775 422.233\n   3.959 200.739\n   4.144 79.411\n   4.328 43.959\n   4.513 14.862\n   4.697 0.000\n",
    "source": {
      "file": "AeroTech_L850W.eng",
      "motorId": "5f4294d20002310000000181",
      "simfileId": "5f4294d20002e90000000083",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000083/",
      "designation": "L850W",
      "manufacturer": "AeroTech",
      "commonName": "L850"
    }
  },
  {
    "eng": "; AeroTech L952W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nL952W 98 427 0 2.73011 5.01222 AT\n   0.141 679.073\n   0.425 801.562\n   0.709 848.474\n   0.994 913.345\n   1.278 981.614\n   1.562 1043.690\n   1.847 1088.114\n   2.131 1112.556\n   2.416 1121.541\n   2.700 1118.573\n   2.984 1100.665\n   3.269 1039.140\n   3.553 965.784\n   3.837 876.793\n   4.122 780.693\n   4.406 693.903\n   4.691 608.030\n   4.975 528.335\n   5.259 463.528\n   5.544 405.769\n   5.828 358.367\n   6.112 279.009\n   6.397 99.897\n   6.681 20.108\n   6.967 3.317\n   7.252 0.000",
    "source": {
      "file": "AeroTech_L952W.eng",
      "motorId": "5f4294d20002310000000185",
      "simfileId": "5f4294d20002e90000000085",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000085/",
      "designation": "L952W",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; AeroTech M2400T\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nM2400T 98 597 0 3.65254 6.4512 AT\n   0.070 2441.945\n   0.211 2495.460\n   0.353 2556.133\n   0.495 2601.596\n   0.636 2637.660\n   0.778 2660.804\n   0.920 2676.486\n   1.061 2687.081\n   1.203 2695.807\n   1.345 2694.493\n   1.486 2684.268\n   1.628 2667.289\n   1.771 2629.961\n   1.914 2578.923\n   2.055 2522.074\n   2.197 2461.704\n   2.339 2393.518\n   2.480 2303.939\n   2.622 2201.610\n   2.764 2097.461\n   2.905 2010.409\n   3.047 1275.776\n   3.189 418.836\n   3.330 17.586\n   3.473 3.669\n   3.616 0.000\n",
    "source": {
      "file": "AeroTech_M2400T.eng",
      "motorId": "5f4294d200023100000001b6",
      "simfileId": "5f4294d20002e90000000093",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000093/",
      "designation": "M2400T",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": "; @TI: 14137.65, @TIa: 14071.08, @TIe: 0.0%, @ThMax: 2137.42, @ThAvg: 1048.203, @Tb: 13.424\n; Exported using ThrustCurveTool, www.ThrustGear.com\nN1048 98 1046 P 7.925 12.777 AT/RCS\n0.0 0.457288\n0.152 0.314574\n0.162 40.2069\n0.164 148.3954\n0.168 598.904\n0.172 890.058\n0.176 995.096\n0.178 1158.031\n0.182 1342.306\n0.19 1556.716\n0.222 1959.8\n0.234 2050.53\n0.254 2111.01\n0.308 2119.9\n0.356 2073.29\n0.47 2091.07\n0.528 1989.543\n0.582 1825.825\n0.648 1733.526\n0.782 1658.07\n0.892 1701.725\n0.914 1633.231\n0.966 1669.558\n1.7839 1594.076\n1.8239 1551.156\n3.1999 1533.43\n5.4538 1378.986\n6.9577 1170.933\n10.9216 424.692\n13.5895 106.0499\n14.6754 12.60914\n16.1354 0.0\n",
    "source": {
      "file": "AeroTech_N1000W.eng",
      "motorId": "5f4294d2000231000000027e",
      "simfileId": "5f4294d20002e900000005c9",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000005c9/",
      "designation": "N1000W",
      "manufacturer": "AeroTech",
      "commonName": "N1000"
    }
  },
  {
    "eng": "N3300R-P 98 1060 P 7.5120000000000005 12.269 AT\r\n   0.036 40.168\r\n   0.078 2887.624\r\n   0.125 3775.78\r\n   0.157 3628.498\r\n   0.2 3534.773\r\n   0.417 3597.256\r\n   0.666 3628.498\r\n   0.962 3668.666\r\n   1.197 3664.203\r\n   1.507 3655.276\r\n   1.9 3619.572\r\n   2.206 3570.478\r\n   2.423 3530.31\r\n   2.637 3423.195\r\n   3.008 3208.967\r\n   3.318 3025.98\r\n   3.617 2820.677\r\n   3.86 2646.617\r\n   3.963 2597.522\r\n   4.024 2468.093\r\n   4.091 2267.253\r\n   4.163 1896.816\r\n   4.284 1124.7\r\n   4.394 343.658\r\n   4.455 129.43\r\n   4.519 0.0",
    "source": {
      "file": "AeroTech_N3300.eng",
      "motorId": "5f4294d2000231000000030d",
      "simfileId": "5f4294d20002e90000000884",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000884/",
      "designation": "N3300R-P",
      "manufacturer": "AeroTech",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Apogee C10 RASP.ENG file made from NAR published data\n;File produced September 4, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nC10 18 50 4-7-10 0.0049 0.0176 Apogee \n0.01 2.712\n0.019 5.842\n0.029 17.116\n0.037 25.72\n0.051 22.535\n0.07 20.446\n0.106 18.983\n0.164 17.085\n0.188 17.085\n0.2 15.824\n0.216 16.036\n0.255 15.602\n0.293 14.35\n0.343 13.503\n0.394 12.655\n0.41 11.605\n0.434 11.605\n0.521 9.287\n0.631 6.34\n0.741 4.021\n0.851 2.119\n0.911 1.48\n0.945 1.264\n0.96 0\n",
    "source": {
      "file": "Apogee_C10.eng",
      "motorId": "5f4294d20002310000000019",
      "simfileId": "5f4294d20002e90000000492",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000492/",
      "designation": "C10",
      "manufacturer": "Apogee Components",
      "commonName": "C10"
    }
  },
  {
    "eng": ";\n;Aerotech E6 RASP.ENG file made from NAR published data\n;File produced July 4, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nE6 24 70 2-4-6-8-100 0.0215 0.0463 Apogee \n0.056 18.59\n0.112 20.12\n0.168 17.575\n0.307 14.38\n0.531 10.45\n0.894 7.696\n1.146 6.244\n1.691 5.808\n2.836 5.663\n3.898 5.517\n4.275 5.227\n4.415 4.937\n5.058 5.082\n5.519 5.227\n5.603 6.679\n5.729 3.921\n5.882 2.323\n5.966 1.016\n6.06 0\n",
    "source": {
      "file": "Apogee_E6.eng",
      "motorId": "5f4294d2000231000000020f",
      "simfileId": "5f4294d20002e90000000495",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000495/",
      "designation": "E6",
      "manufacturer": "Apogee Components",
      "commonName": "E6"
    }
  },
  {
    "eng": "; Pro-54-3G White Thunder\r\n1266-J760-WT-19A 54 329 8-10-12-14-16-18-19 0.5760 1.0768 CTI\r\n   0.012 600.251\r\n   0.019 833.333\r\n   0.026 938.596\r\n   0.04 794.486\r\n   0.054 756.892\r\n   0.094 778.195\r\n   0.129 800.752\r\n   0.165 813.283\r\n   0.218 825.815\r\n   0.279 830.827\r\n   0.377 835.84\r\n   0.496 837.093\r\n   0.617 829.574\r\n   0.709 819.549\r\n   0.811 802.005\r\n   0.917 785.714\r\n   1.041 764.411\r\n   1.201 750.627\r\n   1.331 741.855\r\n   1.455 729.323\r\n   1.488 729.323\r\n   1.514 735.589\r\n   1.556 749.373\r\n   1.568 729.323\r\n   1.575 665.414\r\n   1.589 533.835\r\n   1.616 327.068\r\n   1.646 122.807\r\n   1.659 72.682\r\n   1.681 30.075\r\n   1.713 6.266\r\n   1.731 0.0",
    "source": {
      "file": "Cesaroni_1266-J760-WT-19A.eng",
      "motorId": "5f4294d200023100000003a8",
      "simfileId": "5f4294d20002e9000000074a",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000074a/",
      "designation": "1266-J760-WT-19A",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nK660  54.0 572.00 7-17 1.17700 1.94900 CTI\n   0.07    1078.90 \n   0.23    1006.47 \n   0.40     966.76 \n   0.80     897.52 \n   1.20     842.72 \n   1.60     794.15 \n   2.01     744.52 \n   2.40     692.27 \n   2.54     671.37 \n   2.68     439.08 \n   2.80     400.68 \n   3.01     386.90 \n   3.20     234.31 \n   3.45     106.65 \n   3.60      44.03 \n   3.69       0.00\n",
    "source": {
      "file": "Cesaroni_2437K660-17A.eng",
      "motorId": "5f4294d20002310000000154",
      "simfileId": "5f4294d20002e90000000143",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000143/",
      "designation": "2437K660-17A",
      "manufacturer": "Cesaroni Technology",
      "commonName": null
    }
  },
  {
    "eng": ";Pro54 6GXL 2546 K300-CL P\n;Longburn\n;Uses a new threaded forward closure\nK300-CL 54 649 0 1.3776 2.27 CTI \n0.036 495.273\n0.132 543.273\n0.265 506.909\n0.734 493.091\n1.258 489.455\n1.811 482.909\n2.467 453.818\n3.737 375.273\n4.705 299.636\n6.047 165.091\n6.474 120.727\n6.829 90.182\n7.323 63.273\n7.72 46.545\n8.309 30.545\n8.37 0\n;\n",
    "source": {
      "file": "Cesaroni_2546K300-P.eng",
      "motorId": "5f4294d2000231000000037f",
      "simfileId": "5f4294d20002e9000000070f",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000070f/",
      "designation": "2546K300-P",
      "manufacturer": "Cesaroni Technology",
      "commonName": "K300"
    }
  },
  {
    "eng": "; Pro38-3G White\n411-I175-WH-14A 38 245 6-8-9-11-12-13 0.22890000000000002 0.4375 CTI\n   0.019 149.422\n   0.038 180.347\n   0.052 166.763\n   0.106 184.971\n   0.148 187.572\n   0.232 187.861\n   0.338 189.017\n   0.518 190.751\n   0.604 192.197\n   0.733 193.353\n   0.877 195.087\n   1.005 193.931\n   1.128 193.353\n   1.333 193.064\n   1.495 190.751\n   1.648 188.15\n   1.79 183.526\n   1.921 178.035\n   2.001 178.324\n   2.043 176.59\n   2.089 151.156\n   2.147 115.318\n   2.212 70.231\n   2.274 47.11\n   2.32 22.832\n   2.368 8.671\n   2.396 3.757\n   2.435 3.179\n   2.5 0.0\n",
    "source": {
      "file": "Cesaroni_411-I175-WH-14A.eng",
      "motorId": "5f4294d200023100000003a0",
      "simfileId": "5f4294d20002e9000000075a",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000075a/",
      "designation": "411I175-14A",
      "manufacturer": "Cesaroni Technology",
      "commonName": "I175"
    }
  },
  {
    "eng": "; CTI Pro54-2G 838 J293BS 13A\nJ293BS 54 237 13-12-11-10-9-8-7-6-5-4-3 0.41600000000000004 0.84 CTI\n   0.019 22.847\n   0.032 250.277\n   0.044 386.32\n   0.06 302.202\n   0.073 256.508\n   0.13 285.586\n   0.266 309.471\n   0.487 318.818\n   0.734 325.049\n   1.432 324.01\n   1.786 309.471\n   2.074 294.933\n   2.33 280.394\n   2.488 273.124\n   2.58 272.086\n   2.634 258.585\n   2.713 163.044\n   2.795 70.618\n   2.852 20.77\n   2.896 0.0\n",
    "source": {
      "file": "Cesaroni_838J293-13A.eng",
      "motorId": "5f4294d200023100000002d8",
      "simfileId": "5f4294d20002e90000000674",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000674/",
      "designation": "838J293-13A",
      "manufacturer": "Cesaroni Technology",
      "commonName": null
    }
  },
  {
    "eng": "H100-IM 38 186 6-8-11-12-15 0.1544 0.327 CTI\r\n0.016 68\r\n0.056 116\r\n0.09 118\r\n0.14 115\r\n0.5 116\r\n0.6 114\r\n1.25 113\r\n2.32 99\r\n2.44 100\r\n2.55 89\r\n2.77 0",
    "source": {
      "file": "Cesaroni_H100.eng",
      "motorId": "5f4294d200023100000002cb",
      "simfileId": "5f4294d20002e90000000656",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000656/",
      "designation": "H100-IM",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";Pro-38 Red Lightning 2 Grain reload\nH120-14A 38 186 14-11-9-7-5 0.1366 0.295 CTI \n0.016 53.023\n0.029 107.113\n0.036 124.55\n0.049 129.532\n0.062 117.789\n0.072 98.217\n0.131 123.838\n0.199 136.649\n0.258 144.122\n0.313 147.681\n0.369 146.257\n0.441 145.19\n0.558 143.411\n0.683 141.631\n0.777 140.92\n0.859 139.14\n0.98 136.293\n1.097 133.091\n1.251 128.82\n1.434 122.771\n1.558 118.856\n1.639 117.077\n1.731 117.077\n1.884 117.077\n1.927 105.334\n1.959 88.964\n1.995 68.325\n2.031 41.991\n2.083 18.505\n2.142 6.761\n2.181 2.135\n2.24 0\n;\n",
    "source": {
      "file": "Cesaroni_H120-14A.eng",
      "motorId": "5f4294d20002310000000218",
      "simfileId": "5f4294d20002e90000000436",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000436/",
      "designation": "261H120-14A",
      "manufacturer": "Cesaroni Technology",
      "commonName": "H120"
    }
  },
  {
    "eng": ";\n;\nI212SS  38.0 245.00 5-7-9-11-14 0.24810 0.47500 CTI\n   0.04     189.66 \n   0.20     207.11 \n   0.40     222.41 \n   0.60     236.62 \n   0.80     249.60 \n   0.95     255.15 \n   1.01     250.22 \n   1.21     233.54 \n   1.40     208.99 \n   1.55     183.99 \n   1.60     168.08 \n   1.63     134.62 \n   1.69      25.86 \n   1.71       0.00",
    "source": {
      "file": "Cesaroni_I212.eng",
      "motorId": "5f4294d200023100000000ba",
      "simfileId": "5f4294d20002e9000000013b",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000013b/",
      "designation": "I212SS",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "I216-CL(I) 38 367 5-7-9-11-14 0.3125 0.601 CTI\r\n0.017 35\r\n0.03 300\r\n0.035 345\r\n0.05 325\r\n0.07 275\r\n0.14 292\r\n0.26 296\r\n0.8 280\r\n1.1 280.4\r\n1.62 255\r\n1.8 226\r\n2.105 210\r\n2.2 195\r\n2.45 80\r\n2.75 36\r\n3.1 0",
    "source": {
      "file": "Cesaroni_I216.eng",
      "motorId": "5f4294d200023100000002cc",
      "simfileId": "5f4294d20002e90000000654",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000654/",
      "designation": "I216-CL(I)",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nI540WT 38 367 7-9-11-13-16 0.3288 0.5982 CTI \n0.03 597.86\n0.04 611.31\n0.06 605.64\n0.12 612.36\n0.24 624.54\n0.36 626\n0.48 623.63\n0.6 616.42\n0.72 598.14\n0.84 583.16\n0.95 568.92\n0.96 558.53\n0.98 533.45\n1.02 436.53\n1.06 303.15\n1.09 184.92\n1.13 74.27\n1.18 0",
    "source": {
      "file": "Cesaroni_I540WT.eng",
      "motorId": "5f4294d200023100000001fb",
      "simfileId": "5f4294d20002e900000002aa",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000002aa/",
      "designation": "I540WT",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nJ285  38.0 367.00 6-8-10-12-15 0.31250 0.59500 CTI\n   0.06     351.01 \n   0.15     346.01 \n   0.25     357.64 \n   0.50     363.90 \n   0.75     369.26 \n   1.03     343.33 \n   1.27     337.07 \n   1.51     317.40 \n   1.75     282.53 \n   1.93     127.86 \n   2.02      84.94 \n   2.25      11.02 \n   2.26       0.00\n",
    "source": {
      "file": "Cesaroni_J285.eng",
      "motorId": "5f4294d20002310000000101",
      "simfileId": "5f4294d20002e90000000137",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000137/",
      "designation": "648J285-15A",
      "manufacturer": "Cesaroni Technology",
      "commonName": "J285"
    }
  },
  {
    "eng": "J420-CL 38 500 6-8-10-12-15 0.522 0.874 CTI \n0.015 360\n0.02 660\n0.035 800\n0.075 660\n0.25 625\n0.7 560\n1.45 495\n1.51 480\n1.62 350\n1.8 220\n1.9 150\n2 120\n2.25 48\n2.62 0\n",
    "source": {
      "file": "Cesaroni_J420-CL.eng",
      "motorId": "5f4294d2000231000000029d",
      "simfileId": "5f4294d20002e90000000633",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000633/",
      "designation": "1008J420-15A",
      "manufacturer": "Cesaroni Technology",
      "commonName": "J420"
    }
  },
  {
    "eng": "; 644-J94-MY  Cesaroni Pro38\n; converted from the ThrustCurve.org RockSim simfile (no RASP file is published)\n644-J94-MY-P 38 367 0 0.3930 0.6600 CTI\n   0.0000 0.000\n   0.0050 19.477\n   0.0140 168.646\n   0.0500 133.967\n   0.1130 133.967\n   0.2030 146.081\n   0.7520 133.967\n   1.7870 116.865\n   3.0750 110.451\n   4.2360 108.314\n   4.8030 77.672\n   5.4740 56.295\n   6.3750 17.577\n   6.8790 6.413\n   6.9280 0.000\n",
    "source": {
      "file": "Cesaroni_J94.eng",
      "motorId": "5f4294d20002310000000416",
      "simfileId": "5f4294d20002e90000000810",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000810/",
      "designation": "644-J94-MY-P",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; From Cesaroni WebPage by C. Kobel 4/23/15\nK1440WT 54 572 8-11-14-17 1.129 1.893 Ces\n   0.015 893.963\n   0.026 1563.355\n   0.030 1671.321\n   0.035 1718.827\n   0.047 1667.003\n   0.063 1628.135\n   0.100 1671.321\n   0.200 1701.552\n   0.300 1705.871\n   0.400 1710.189\n   0.500 1705.871\n   0.600 1701.552\n   0.700 1684.277\n   0.800 1658.366\n   0.900 1619.498\n   1.000 1597.904\n   1.100 1546.080\n   1.221 1498.575\n   1.300 1144.445\n   1.337 1062.39\n   1.400 1058.072\n   1.447 1053.753\n   1.500 716.898\n   1.543 578.700\n   1.600 306.625\n   1.644 125.241\n   1.700 0.0\n",
    "source": {
      "file": "Cesaroni_K1440.eng",
      "motorId": "5f4294d20002310000000261",
      "simfileId": "5f4294d20002e90000000852",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000852/",
      "designation": "K1440",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; Pro-54-5G White Long Burn Plugged\n2021-K261-WH_LB-P 54 488 P 1.1519 1.9317 CTI\n   0.035 283.061\n   0.069 321.706\n   0.124 345.797\n   0.228 336.763\n   0.525 347.302\n   0.85 359.348\n   1.334 356.336\n   1.79 359.348\n   2.039 354.329\n   2.412 353.325\n   2.793 349.812\n   3.131 344.291\n   3.774 323.714\n   4.652 278.545\n   5.281 230.866\n   5.571 206.775\n   5.993 166.625\n   6.325 137.516\n   6.615 102.384\n   7.085 55.207\n   7.362 35.634\n   7.694 20.577\n   8.129 9.536\n   8.502 2.509\n   8.979 0.0\n",
    "source": {
      "file": "Cesaroni_K261.eng",
      "motorId": "5f4294d200023100000003a6",
      "simfileId": "5f4294d20002e9000000074e",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000074e/",
      "designation": "K261",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nK445  54.0 404.00 7-17 0.79200 1.39800 CTI\n   0.05     664.83 \n   0.19     640.68 \n   0.48     622.98 \n   1.00     576.29 \n   1.51     515.12 \n   2.00     442.68 \n   2.50     392.26 \n   3.02     350.93 \n   3.13     339.66 \n   3.31     210.88 \n   3.47      78.88 \n   3.67       0.00",
    "source": {
      "file": "Cesaroni_K445.eng",
      "motorId": "5f4294d2000231000000013b",
      "simfileId": "5f4294d20002e90000000141",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000141/",
      "designation": "K445",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nK530SS  54.0 404.00 6-16 1.02500 1.63980 CTI\n   0.05     533.59 \n   0.09     503.98 \n   0.29     514.09 \n   0.60     534.31 \n   0.90     557.41 \n   1.20     577.63 \n   1.50     587.74 \n   1.80     596.40 \n   2.10     535.44 \n   2.31     502.54 \n   2.47     551.63 \n   2.56     393.94 \n   2.60     274.37 \n   2.64     137.19 \n   2.67       0.00\n",
    "source": {
      "file": "Cesaroni_K530.eng",
      "motorId": "5f4294d20002310000000145",
      "simfileId": "5f4294d20002e90000000147",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000147/",
      "designation": "K530",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; C-Star 75mm 3G\n; 4263-L1350-CS-P\n4263-L1350-CS-P 75 486 P 2.0245 3.5707 CTI\n   0.016 1421.724\n   0.034 1345.218\n   0.049 1502.479\n   0.081 1415.348\n   0.21 1432.349\n   0.453 1432.349\n   0.809 1462.102\n   1.07 1534.357\n   1.28 1540.732\n   2.661 1283.589\n   2.843 1277.214\n   2.932 1115.702\n   3.037 488.784\n   3.163 82.881\n   3.284 0.0\n",
    "source": {
      "file": "Cesaroni_L1350.eng",
      "motorId": "5f4294d200023100000003dc",
      "simfileId": "5f4294d20002e900000007c6",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007c6/",
      "designation": "L1350",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nL730  54.0 649.00 0 1.35100 2.24700 CTI\n   0.00      81.36 \n   0.01    1079.71 \n   0.02    1216.59 \n   0.04    1154.68 \n   0.20    1127.51 \n   0.45    1055.11 \n   0.60    1028.17 \n   0.75     995.24 \n   1.00     959.33 \n   1.50     898.71 \n   2.00     830.70 \n   2.50     730.76 \n   2.60     592.55 \n   2.70     510.96 \n   2.90     487.88 \n   3.00     405.72 \n   3.10     299.80 \n   3.20     296.09 \n   3.30     251.85 \n   3.40     171.70 \n   3.50     165.26 \n   3.60     139.38 \n   3.65     117.77 \n   3.77      45.38 \n   3.77       0.00\n",
    "source": {
      "file": "Cesaroni_L730.eng",
      "motorId": "5f4294d2000231000000017c",
      "simfileId": "5f4294d20002e90000000144",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000144/",
      "designation": "L730",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "M1670-BS 75 757 0 3.101 5.231 CTI \n0.055 100\n0.092 1500\n0.1 2000\n0.15 2200\n0.2 1800\n0.5 1950\n1 2034\n1.5 2000\n2 1900\n2.5 1760\n2.9 1700\n3 1650\n3.3 530\n3.4 350\n3.9 0\n",
    "source": {
      "file": "Cesaroni_M1670.eng",
      "motorId": "5f4294d20002310000000296",
      "simfileId": "5f4294d20002e9000000062c",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000062c/",
      "designation": "M1670",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; Imax Pro75 6GXL\n; 9977 M2245-IM-P\n9977-M2245-IM-P 75 1025 P 5.309 8.182 CTI\n   0.043 3045.655\n   0.136 2629.813\n   1.393 3003.3\n   2.168 3007.151\n   2.708 2972.497\n   2.837 2883.938\n   3.152 1955.996\n   3.397 1409.241\n   3.878 562.156\n   4.371 0.0\n",
    "source": {
      "file": "Cesaroni_M2245.eng",
      "motorId": "5f4294d200023100000003e9",
      "simfileId": "5f4294d20002e900000007b5",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007b5/",
      "designation": "M2245",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; Pro98-4G 9994M3400-WT P\nM3400-WT 98 702 P 4.766 8.108 CTI\n   0.021 3639.453\n   0.049 3360.146\n   0.111 3300.899\n   0.374 3478.64\n   0.909 3774.874\n   1.059 3897.6\n   1.208 3884.904\n   1.571 3787.57\n   2.168 3402.465\n   2.467 3245.884\n   2.709 3292.435\n   2.734 3254.348\n   2.821 1032.589\n   2.876 550.15\n   2.93 165.045\n   2.99 0.0\n",
    "source": {
      "file": "Cesaroni_M3400.eng",
      "motorId": "5f4294d20002310000000318",
      "simfileId": "5f4294d20002e900000006f9",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006f9/",
      "designation": "M3400",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; Pro98-6GXL 14263N3400-SK P\r\nN3400-SK 98 1239 P 8.471 13.972 CTI\r\n   0.055 3602.205\r\n   0.177 3060.167\r\n   0.608 3397.34\r\n   1.537 3811.337\r\n   2.252 3973.522\r\n   2.86 3760.121\r\n   3.152 3597.937\r\n   3.545 3346.124\r\n   3.71 3627.813\r\n   3.837 2868.106\r\n   3.884 1907.803\r\n   3.999 1510.877\r\n   4.188 273.153\r\n   4.28 81.092\r\n   4.3 0.0",
    "source": {
      "file": "Cesaroni_N3400.eng",
      "motorId": "5f4294d200023100000002f9",
      "simfileId": "5f4294d20002e900000006c2",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006c2/",
      "designation": "N3400-SK",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": "; Pro98-6GXL 17631N3800-BS P\r\nN3800-BS 98 1239 P 8.71 14.261000000000001 CTI\r\n   0.016 2671.724\r\n   0.069 4632.012\r\n   0.159 4360.745\r\n   0.293 4355.626\r\n   1.11 4591.066\r\n   1.48 4703.667\r\n   1.847 4729.258\r\n   2.384 4683.194\r\n   2.628 4550.12\r\n   3.141 4135.542\r\n   3.343 4043.413\r\n   3.434 4022.94\r\n   3.497 3787.501\r\n   3.582 3204.021\r\n   3.681 2809.916\r\n   3.853 2385.102\r\n   4.042 1458.7\r\n   4.198 972.467\r\n   4.338 946.875\r\n   4.401 864.983\r\n   4.604 378.75\r\n   4.673 230.321\r\n   4.7 0.0",
    "source": {
      "file": "Cesaroni_N3800.eng",
      "motorId": "5f4294d20002310000000319",
      "simfileId": "5f4294d20002e900000006fb",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006fb/",
      "designation": "N3800-BS",
      "manufacturer": "Cesaroni",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Estes 1/2A3T RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\n1/2A3T 13 45 2-4 0.002 0.0066 Estes \n0.024 0.501\n0.042 1.454\n0.064 3.009\n0.076 4.062\n0.088 4.914\n0.093 5.065\n0.103 6.068\n0.112 6.87\n0.117 7.021\n0.126 7.62\n0.137 7.472\n0.146 6.87\n0.153 6.118\n0.159 5.065\n0.166 4.363\n0.179 3.66\n0.197 2.908\n0.222 2.256\n0.25 2.156\n0.277 2.106\n0.294 2.056\n0.304 2.156\n0.316 1.955\n0.326 1.554\n0.339 1.053\n0.35 0.651\n0.36 0\n",
    "source": {
      "file": "Estes_1_2A3.eng",
      "motorId": "5f4294d20002310000000006",
      "simfileId": "5f4294d20002e900000004e0",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e0/",
      "designation": "1/2A3",
      "manufacturer": "Estes Industries",
      "commonName": "1/2A3"
    }
  },
  {
    "eng": ";Estes 1/4A3T RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\n1/4A3T 13 45 3 0.00083 0.0061 Estes \n0.016 0.243\n0.044 1.164\n0.08 2.698\n0.088 2.851\n0.096 3.312\n0.105 3.804\n0.116 4.325\n0.129 4.754\n0.131 4.754\n0.135 4.95\n0.139 4.815\n0.143 4.814\n0.149 4.66\n0.157 4.289\n0.173 3.548\n0.187 2.808\n0.194 2.592\n0.197 2.13\n0.202 1.913\n0.206 1.512\n0.213 1.389\n0.218 1.112\n0.227 0.802\n0.236 0.493\n0.241 0.277\n0.25 0\n",
    "source": {
      "file": "Estes_1_4A3.eng",
      "motorId": "5f4294d20002310000000004",
      "simfileId": "5f4294d20002e900000004df",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004df/",
      "designation": "1/4A3",
      "manufacturer": "Estes Industries",
      "commonName": "1/4A3"
    }
  },
  {
    "eng": ";Estes A10T RASP.ENG file made from NAR published data\n; File produced March 3, 2011\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nA10T 13 45 0 .0038 .00525 E\n0.016 0.492\n0.040 0.752\n0.062 0.962\n0.078 2.051\n0.096 2.858\n0.122 4.611\n0.138 6.054\n0.162 8.100\n0.180 9.502\n0.198 9.740\n0.212 8.204\n0.224 4.530\n0.238 2.054\n0.268 1.414\n0.292 1.385\n0.324 1.067\n0.364 1.099\n0.396 0.957\n0.446 0.995\n0.490 0.901\n0.574 0.909\n0.676 0.909\n0.782 1.031\n0.886 1.048\n0.980 1.029\n1.006 0.995\n1.038 1.049\n1.050 0.741\n1.060 0.000\n",
    "source": {
      "file": "Estes_A10.eng",
      "motorId": "5f4294d2000231000000000c",
      "simfileId": "624aff26a49a690004b83002",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/624aff26a49a690004b83002/",
      "designation": "A10",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Estes A3T RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nA3T 13 45 4 0.0033 0.0085 Estes \n0.024 0.195\n0.048 0.899\n0.086 2.658\n0.11 4.183\n0.14 5.83\n0.159 5.395\n0.18 4.301\n0.199 3.635\n0.215 2.736\n0.234 2.267\n0.258 2.15\n0.315 2.072\n0.441 1.993\n0.554 2.033\n0.605 2.072\n0.673 1.954\n0.764 1.954\n0.874 2.072\n0.931 2.15\n0.953 2.072\n0.966 1.719\n0.977 1.173\n0.993 0.547\n1.01 0\n",
    "source": {
      "file": "Estes_A3.eng",
      "motorId": "5f4294d20002310000000009",
      "simfileId": "5f4294d20002e900000004e2",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e2/",
      "designation": "A3",
      "manufacturer": "Estes Industries",
      "commonName": "A3"
    }
  },
  {
    "eng": ";\r\n;Estes A8 RASP.ENG file made from NAR published data\r\n;File produced October 3, 2000\r\n;The total impulse, peak thrust, average thrust and burn time are\r\n;the same as the averaged static test data on the NAR web site in\r\n;the certification file. The curve drawn with these data points is as\r\n;close to the certification curve as can be with such a limited\r\n;number of points (32) allowed with wRASP up to v1.6.\r\nA8 18 70 3-5 0.0033 0.01635 Estes \r\n0.041 0.512\r\n0.084 2.115\r\n0.127 4.358\r\n0.166 6.794\r\n0.192 8.588\r\n0.206 9.294\r\n0.226 9.73\r\n0.236 8.845\r\n0.247 7.179\r\n0.261 5.063\r\n0.277 3.717\r\n0.306 3.205\r\n0.351 2.884\r\n0.405 2.499\r\n0.467 2.371\r\n0.532 2.307\r\n0.589 2.371\r\n0.632 2.371\r\n0.652 2.243\r\n0.668 1.794\r\n0.684 1.153\r\n0.703 0.448\r\n0.73 0",
    "source": {
      "file": "Estes_A8.eng",
      "motorId": "5f4294d2000231000000000b",
      "simfileId": "5f4294d20002e900000004e3",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e3/",
      "designation": "A8",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Estes B4 RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nB4 18 70 2-4 0.006 0.0189 Estes \n0.02 0.418\n0.04 1.673\n0.065 4.076\n0.085 6.69\n0.105 9.304\n0.119 11.496\n0.136 12.75\n0.153 11.916\n0.173 10.666\n0.187 9.304\n0.198 7.214\n0.207 5.645\n0.226 4.809\n0.258 4.182\n0.326 3.763\n0.422 3.554\n0.549 3.345\n0.665 3.345\n0.776 3.345\n0.863 3.345\n0.94 3.449\n0.991 3.449\n1.002 2.404\n1.01 1.254\n1.03 0\n",
    "source": {
      "file": "Estes_B4.eng",
      "motorId": "5f4294d2000231000000000e",
      "simfileId": "5f4294d20002e900000004e5",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e5/",
      "designation": "B4",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": "; Estes B6-0 from NAR data by Mark Koelsch\nB6-0 18 70 0 0.0056 0.0156 E\n   0.036 1.364\n   0.064 2.727\n   0.082 4.215\n   0.111 6.694\n   0.135 9.05\n   0.146 9.545\n   0.172 11.901\n   0.181 12.149\n   0.191 11.901\n   0.211 9.174\n   0.239 7.314\n   0.264 6.074\n   0.275 5.95\n   0.333 5.207\n   0.394 4.835\n   0.445 4.835\n   0.556 4.339\n   0.667 4.587\n   0.723 4.339\n   0.78 4.339\n   0.793 4.091\n   0.812 2.603\n   0.833 1.24\n   0.857 0.0\n",
    "source": {
      "file": "Estes_B6.eng",
      "motorId": "5f4294d20002310000000010",
      "simfileId": "5f4294d20002e90000000414",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000414/",
      "designation": "B6",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": ";\n;ESTES C11 RASP.ENG file made from NAR published data\n;File produced JANUARY 1, 2002\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nC11 24 70 0-3-5-7 0.012 0.0353 Estes \n0.034 1.692\n0.066 3.782\n0.107 7.566\n0.145 10.946\n0.183 14.832\n0.214 17.618\n0.226 18.213\n0.256 20.107\n0.281 21.208\n0.298 21.73\n0.306 20.206\n0.323 17.321\n0.337 14.931\n0.358 13.236\n0.385 11.947\n0.413 11.65\n0.468 10.946\n0.539 10.45\n0.619 10.648\n0.683 10.648\n0.715 10.648\n0.726 10.053\n0.74 8.163\n0.758 5.773\n0.778 3.185\n0.795 1.394\n0.81 0\n",
    "source": {
      "file": "Estes_C11.eng",
      "motorId": "5f4294d2000231000000001a",
      "simfileId": "5f4294d20002e900000004e8",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e8/",
      "designation": "C11",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": "; Estes C6 RASP.ENG file made from NAR published data\n; File produced October 3, 2000\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nC6 18 70 0-3-5-7 .0108 .0231 E\n0.031 0.946\n0.092 4.826\n0.139 9.936\n0.192 14.090\n0.209 11.446\n0.231 7.381\n0.248 6.151\n0.292 5.489\n0.370 4.921\n0.475 4.448\n0.671 4.258\n0.702 4.542\n0.723 4.164\n0.850 4.448\n1.063 4.353\n1.211 4.353\n1.242 4.069\n1.303 4.258\n1.468 4.353\n1.656 4.448\n1.821 4.448\n1.834 2.933\n1.847 1.325\n1.860 0.000\n",
    "source": {
      "file": "Estes_C6.eng",
      "motorId": "5f4294d20002310000000015",
      "simfileId": "69eb2379c7d63000021d8c29",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/69eb2379c7d63000021d8c29/",
      "designation": "C6",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": ";\n;Estes D12 RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD12 24 70 0-3-5-7 0.0211 0.0426 Estes \n0.049 2.569\n0.116 9.369\n0.184 17.275\n0.237 24.258\n0.282 29.73\n0.297 27.01\n0.311 22.589\n0.322 17.99\n0.348 14.126\n0.386 12.099\n0.442 10.808\n0.546 9.876\n0.718 9.306\n0.879 9.105\n1.066 8.901\n1.257 8.698\n1.436 8.31\n1.59 8.294\n1.612 4.613\n1.65 0\n",
    "source": {
      "file": "Estes_D12.eng",
      "motorId": "5f4294d20002310000000020",
      "simfileId": "5f4294d20002e900000004ea",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004ea/",
      "designation": "D12",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": "; Based on NAR Published Data, 7/31/12, C. J. Kobel\nE12 24 95 0-4-6-8 0.0359 0.0599 Estes\n   0.052 5.045\n   0.096 9.910\n   0.196 24.144\n   0.251 31.351\n   0.287 32.973\n   0.300 29.910\n   0.344 17.117\n   0.370 14.414\n   0.400 12.973\n   0.500 11.712\n   0.600 11.171\n   0.700 10.631\n   0.800 10.09\n   0.900 9.73\n   1.000 9.55\n   1.101 9.91\n   1.200 9.55\n   1.300 9.73\n   1.400 9.73\n   1.500 9.73\n   1.600 9.73\n   1.700 9.55\n   1.800 9.73\n   1.900 9.73\n   2.000 9.55\n   2.100 9.55\n   2.200 9.73\n   2.300 9.19\n   2.375 9.37\n   2.400 5.95\n   2.440 0.0\n",
    "source": {
      "file": "Estes_E12.eng",
      "motorId": "5f4294d200023100000003e3",
      "simfileId": "5f4294d20002e900000007ad",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007ad/",
      "designation": "E12",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": "; File produced, 2013\r\n; The total impulse, peak thrust, average thrust and burn time are\r\n; the same as the averaged static test data on the NAR web site in\r\n; the certification file. The curve drawn with these data points is as\r\n; close to the certification curve as can be with such a limited\r\n; number of points (32) allowed with wRASP up to v1.6.\r\nE16 29 114 0-4-6-8 .0400 .08200 E\r\n0.150 1.371\r\n0.186 1.920\r\n0.206 3.387\r\n0.242 5.587\r\n0.252 7.422\r\n0.277 8.705\r\n0.333 13.474\r\n0.359 15.858\r\n0.374 16.592\r\n0.394 18.609\r\n0.435 21.544\r\n0.476 24.661\r\n0.521 26.440\r\n0.643 21.720\r\n0.725 20.432\r\n0.821 19.511\r\n0.898 18.958\r\n1.025 18.219\r\n1.142 18.032\r\n1.259 17.844\r\n1.396 17.472\r\n1.569 17.282\r\n1.757 17.275\r\n1.895 17.086\r\n2.027 17.816\r\n2.042 12.494\r\n2.052 8.457\r\n2.063 4.970\r\n2.090 0.000",
    "source": {
      "file": "Estes_E16.eng",
      "motorId": "5f4294d200023100000003f8",
      "simfileId": "5f4294d20002e900000007e6",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007e6/",
      "designation": "E16",
      "manufacturer": "Estes",
      "commonName": null
    }
  },
  {
    "eng": "; Estes E9-0 by Mark Koelsch from NAR data\nE9-0 24 95 0 0.0358 0.056799999999999996 E\n   0.046 1.913\n   0.235 16.696\n   0.273 18.435\n   0.326 14.957\n   0.38 12.174\n   0.44 10.435\n   0.835 9.043\n   1.093 8.87\n   1.496 8.696\n   1.997 8.696\n   2.498 8.696\n   3.014 9.217\n   3.037 5.043\n   3.067 1.217\n   3.09 0.0\n",
    "source": {
      "file": "Estes_E9.eng",
      "motorId": "5f4294d20002310000000028",
      "simfileId": "5f4294d20002e90000000416",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000416/",
      "designation": "E9",
      "manufacturer": "Estes Industries",
      "commonName": null
    }
  },
  {
    "eng": "; Estes F15 RASP.ENG file made from NAR published data\r\n; File produced, 2013\r\n; The total impulse, peak thrust, average thrust and burn time are\r\n; the same as the averaged static test data on the NAR web site in\r\n; the certification file. The curve drawn with these data points is as\r\n; close to the certification curve as can be with such a limited\r\n; number of points (32) allowed with wRASP up to v1.6.\r\nF15 29 114 0-4-6-8 .0600 .10300 E\r\n0.148 7.638\r\n0.228 12.253\r\n0.294 16.391\r\n0.353 20.210\r\n0.382 22.756\r\n0.419 25.260\r\n0.477 23.074\r\n0.520 20.845\r\n0.593 19.093\r\n0.688 17.500\r\n0.855 16.225\r\n1.037 15.427\r\n1.205 14.948\r\n1.423 14.627\r\n1.452 15.741\r\n1.503 14.785\r\n1.736 14.623\r\n1.955 14.303\r\n2.210 14.141\r\n2.494 13.819\r\n2.763 13.338\r\n3.120 13.334\r\n3.382 13.013\r\n3.404 9.352\r\n3.418 4.895\r\n3.450 0.000",
    "source": {
      "file": "Estes_F15.eng",
      "motorId": "5f4294d200023100000003f2",
      "simfileId": "5f4294d20002e900000007e5",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007e5/",
      "designation": "F15",
      "manufacturer": "Estes",
      "commonName": null
    }
  },
  {
    "eng": "; HyperTek L540 (2800/75-172-L)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nL540 75 1387 0 2.52224 5.05792 HT\n   0.191 685.548\n   0.574 665.171\n   0.957 635.467\n   1.341 634.122\n   1.725 656.225\n   2.109 706.931\n   2.493 696.526\n   2.876 777.726\n   3.260 775.919\n   3.645 781.611\n   4.028 712.736\n   4.411 695.555\n   4.796 701.251\n   5.180 645.985\n   5.564 607.757\n   5.947 546.408\n   6.331 387.372\n   6.716 234.214\n   7.099 181.086\n   7.482 139.253\n   7.867 106.109\n   8.251 78.293\n   8.634 54.851\n   9.018 36.384\n   9.402 20.375\n   9.786 0.000\n",
    "source": {
      "file": "Hypertek_2800CC172L-L540.eng",
      "motorId": "5f4294d20002310000000172",
      "simfileId": "5f4294d20002e900000000ed",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000000ed/",
      "designation": "2800CC172L-L540",
      "manufacturer": "Hypertek",
      "commonName": "L540"
    }
  },
  {
    "eng": "G66LR 38 122.2 5-15 0.07200000000000001 0.25 Loki\r\n   0.01 4.448\r\n   0.027 3.14\r\n   0.051 12.298\r\n   0.07 22.764\r\n   0.092 45.006\r\n   0.104 66.723\r\n   0.111 80.068\r\n   0.13 89.488\r\n   0.145 97.861\r\n   0.176 106.496\r\n   0.21 112.252\r\n   0.246 114.607\r\n   0.287 115.654\r\n   0.359 113.299\r\n   0.506 106.757\r\n   0.598 102.571\r\n   0.757 94.721\r\n   1.006 80.853\r\n   1.196 66.462\r\n   1.473 44.482\r\n   1.51 41.081\r\n   1.691 26.428\r\n   1.763 21.456\r\n   1.823 16.746\r\n   1.879 14.13\r\n   2.016 7.326\r\n   2.091 4.448\r\n   2.117 4.71\r\n   2.129 0.0",
    "source": {
      "file": "Loki_G66.eng",
      "motorId": "5f4294d20002310000000449",
      "simfileId": "5f4294d20002e90000000864",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000864/",
      "designation": "G66LR",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": ";\nJ528 38 406 5-8-10-13-17 0.372 0.752 Loki \n0.01 704.2\n0.02 1019\n0.03 983.9\n0.05 881.1\n0.1 797.5\n0.15 771.7\n0.17 765.72\n0.21 765.72\n0.25 778.2\n0.42 789.28\n0.51 771.61\n0.6 756.89\n0.66 751\n0.71 762.78\n0.76 697.99\n0.8 665.59\n0.84 612.58\n0.92 488.88\n0.95 385.81\n1.02 282.73\n1.06 179.65\n1.14 53.01\n1.19 35.34\n1.23 32.2\n1.25 0\n",
    "source": {
      "file": "Loki_J528.eng",
      "motorId": "5f4294d20002310000000123",
      "simfileId": "5f4294d20002e90000000127",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000127/",
      "designation": "J528",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": "K1127LB 38 625.5 P 0.624 1.172 Loki\r\n   0.009 77.978\r\n   0.021 1002.962\r\n   0.033 1368.654\r\n   0.045 1210.008\r\n   0.058 1365.965\r\n   0.067 1263.786\r\n   0.08 1360.587\r\n   0.092 1255.719\r\n   0.105 1331.009\r\n   0.117 1242.275\r\n   0.13 1312.186\r\n   0.142 1261.097\r\n   0.155 1304.12\r\n   0.167 1261.097\r\n   0.218 1290.675\r\n   0.395 1325.631\r\n   0.542 1368.654\r\n   0.689 1392.854\r\n   0.726 1382.098\r\n   0.755 1344.453\r\n   0.814 1110.518\r\n   0.867 949.184\r\n   0.874 1099.763\r\n   0.883 962.629\r\n   0.908 847.006\r\n   0.989 548.537\r\n   0.997 363.002\r\n   1.003 715.249\r\n   1.014 494.759\r\n   1.048 406.025\r\n   1.091 352.247\r\n   1.152 228.557\r\n   1.198 158.645\r\n   1.244 69.912\r\n   1.286 32.267\r\n   1.37 0.0",
    "source": {
      "file": "Loki_K1127.eng",
      "motorId": "5f4294d2000231000000043a",
      "simfileId": "5f4294d20002e90000000836",
      "license": "free",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000836/",
      "designation": "K1127LB",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": "; 38/1200\nK627LR 38 625.5 5-7-11-14 0.6880000000000001 1.236 Loki\n   0.014 735.02\n   0.034 989.33\n   0.073 983.128\n   0.166 905.594\n   0.298 840.465\n   0.501 806.351\n   0.746 815.655\n   1.002 824.959\n   1.193 843.567\n   1.258 849.77\n   1.303 831.161\n   1.348 784.641\n   1.5 669.891\n   1.756 437.29\n   1.951 276.02\n   2.004 245.007\n   2.086 210.892\n   2.142 182.98\n   2.252 105.446\n   2.322 74.432\n   2.443 49.622\n   2.499 27.912\n   2.564 0.0\n",
    "source": {
      "file": "Loki_K627.eng",
      "motorId": "5f4294d20002310000000446",
      "simfileId": "5f4294d20002e90000000861",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000861/",
      "designation": "K627",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nL1400 54 726 0 1.4 2.54 Loki \n0.00580046 1606.3\n0.11891 1535.7\n0.327726 1535.7\n0.49884 1588.65\n1.00058 1782.82\n1.40661 1906.38\n1.49942 1376.83\n1.60673 953.19\n1.74594 547.202\n1.90545 335.382\n1.99826 211.82\n2 0\n",
    "source": {
      "file": "Loki_L1400.eng",
      "motorId": "5f4294d20002310000000193",
      "simfileId": "5f4294d20002e9000000012c",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000012c/",
      "designation": "L1400",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": ";\n;\nM1882 75 785 0 3.12979 5.53383 Loki \n0.01 4.8\n0.0174014 2579.22\n0.0696056 2392.32\n0.232019 2298.87\n0.50464 2261.49\n0.771462 2298.87\n0.986079 2411.01\n1.1891 2579.22\n1.49652 2597.91\n1.72854 2485.77\n2.00116 2354.94\n2.5 1644.72\n2.99884 242.97\n3.25 0\n",
    "source": {
      "file": "Loki_M1882.eng",
      "motorId": "5f4294d200023100000001ae",
      "simfileId": "5f4294d20002e9000000012b",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000012b/",
      "designation": "M1882",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": "M2550-LB 76 785 0 3.13 5.53 Loki \n0.00776398 2974.14\n0.0621118 2887.93\n0.427019 2887.93\n0.861801 3017.24\n1.49845 2974.14\n2.11957 2413.79\n2.45342 474.138\n2.6 0\n",
    "source": {
      "file": "Loki_M2550.eng",
      "motorId": "5f4294d2000231000000024f",
      "simfileId": "5f4294d20002e900000005df",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000005df/",
      "designation": "M2550",
      "manufacturer": "Loki",
      "commonName": null
    }
  },
  {
    "eng": "; TMT Certified 5-12-2018 10C12\nC12 18 78.6 4-6-8 0.010400000000000001 0.0237 Q\n   0.012 0.342\n   0.023 1.796\n   0.036 5.218\n   0.05 8.127\n   0.051 9.41\n   0.061 10.351\n   0.088 9.752\n   0.099 9.752\n   0.144 10.265\n   0.165 10.864\n   0.183 11.634\n   0.334 13.687\n   0.501 14.628\n   0.552 15.056\n   0.582 14.628\n   0.593 15.227\n   0.618 15.056\n   0.664 15.74\n   0.702 17.536\n   0.711 17.707\n   0.721 16.852\n   0.727 14.799\n   0.739 11.035\n   0.754 7.271\n   0.765 5.304\n   0.782 3.336\n   0.8 2.053\n   0.823 1.283\n   0.848 0.77\n   0.889 0.0\n",
    "source": {
      "file": "Quest_C12.eng",
      "motorId": "5f4294d2000231000000045e",
      "simfileId": "5f4294d20002e900000008a4",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000008a4/",
      "designation": "C12",
      "manufacturer": "Quest Aerospace",
      "commonName": "C12"
    }
  },
  {
    "eng": "; Quest C6-0 from NAR data\nC6-0 18 70 0 0.0083 0.0216 Q\n   0.02 0.497\n   0.057 2.539\n   0.089 5.132\n   0.129 7.947\n   0.159 9.437\n   0.171 21.247\n   0.181 23.234\n   0.194 22.958\n   0.204 22.185\n   0.218 19.592\n   0.233 17.881\n   0.258 10.486\n   0.308 2.428\n   0.338 2.539\n   0.385 2.98\n   0.412 3.091\n   0.442 3.422\n   0.459 2.98\n   0.536 3.256\n   0.732 3.311\n   0.747 2.483\n   0.78 2.98\n   1.323 3.587\n   1.365 2.815\n   1.887 3.808\n   1.974 3.256\n   2.1 3.532\n   2.227 3.201\n   2.247 0.0\n",
    "source": {
      "file": "Quest_C6.eng",
      "motorId": "5f4294d20002310000000016",
      "simfileId": "5f4294d20002e9000000041c",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000041c/",
      "designation": "C6",
      "manufacturer": "Quest Aerospace",
      "commonName": null
    }
  },
  {
    "eng": "; TMT Certified 5-12-2018 12D16\nD16 18 78.6 4-6-8 0.0125 0.0257 Q\n   0.007 0.411\n   0.021 1.745\n   0.028 8.828\n   0.031 11.497\n   0.04 12.113\n   0.051 13.755\n   0.079 13.037\n   0.167 14.782\n   0.203 16.116\n   0.221 16.014\n   0.271 17.553\n   0.284 18.169\n   0.296 17.553\n   0.334 18.477\n   0.397 19.504\n   0.501 20.736\n   0.618 22.275\n   0.636 22.07\n   0.656 20.941\n   0.673 17.759\n   0.689 13.345\n   0.707 9.033\n   0.724 6.159\n   0.742 3.798\n   0.77 1.95\n   0.803 0.821\n   0.838 0.0\n",
    "source": {
      "file": "Quest_D16.eng",
      "motorId": "5f4294d2000231000000045f",
      "simfileId": "5f4294d20002e90000000893",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000893/",
      "designation": "D16",
      "manufacturer": "Quest Aerospace",
      "commonName": "D16"
    }
  },
  {
    "eng": "; QUEST D5 RASP.ENG FILE\r\n; The total impulse, peak thrust, average thrust and burn time are\r\n; the same as the averaged static test data on the NAR web site in\r\n; the certification file. The curve drawn with these data points is as\r\n; close to the certification curve as can be with such a limited\r\n; number of points (32) allowed with wRASP up to v1.6.\r\nD5 20 96 4-6 0.0240 0.0451 QUEST\r\n0.010 1.014\r\n0.122 2.652\r\n0.172 4.836\r\n0.273 7.723\r\n0.331 10.610\r\n0.390 13.809\r\n0.448 16.800\r\n0.480 12.403\r\n0.484 8.266\r\n0.517 5.221\r\n0.713 4.125\r\n0.974 4.121\r\n1.135 3.338\r\n1.324 3.101\r\n1.550 3.254\r\n1.971 3.169\r\n2.393 3.162\r\n2.752 3.391\r\n3.069 3.386\r\n3.547 3.301\r\n3.694 3.064\r\n3.948 3.294\r\n4.215 3.290\r\n4.412 3.287\r\n4.496 2.505\r\n4.586 1.801\r\n4.610 0.000\r\n;",
    "source": {
      "file": "Quest_D5.eng",
      "motorId": "5f4294d20002310000000376",
      "simfileId": "5f4294d20002e900000006fd",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000006fd/",
      "designation": "D5",
      "manufacturer": "Quest",
      "commonName": null
    }
  },
  {
    "eng": "; From TMT letter June 3 2022\nE35 24 112.8 5,8,11 0.0254 0.0551 Quest\n   0.001 0.626\n   0.028 3.962\n   0.04 13.136\n   0.051 29.608\n   0.178 34.821\n   0.321 36.489\n   0.516 37.74\n   0.712 40.242\n   0.854 41.911\n   0.947 43.579\n   0.979 46.498\n   0.999 41.911\n   1.018 33.779\n   1.04 26.481\n   1.069 19.6\n   1.104 9.383\n   1.122 3.128\n   1.141 0.0\n",
    "source": {
      "file": "Quest_E35W.eng",
      "motorId": "629ee7b1e0d0450004036826",
      "simfileId": "62a020cfe0d0450004037025",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/62a020cfe0d0450004037025/",
      "designation": "E35W",
      "manufacturer": "Quest Aerospace",
      "commonName": "E35"
    }
  },
  {
    "eng": "; From TMT letter June 3 2022\nF41 24 114.3 5,8,11 0.03 0.060700000000000004 Quest\n   0.018 0.679\n   0.031 8.821\n   0.048 25.558\n   0.07 30.308\n   0.099 33.249\n   0.145 34.832\n   0.231 36.641\n   0.409 41.843\n   0.647 45.236\n   0.884 47.498\n   0.947 47.724\n   0.995 51.569\n   1.032 51.343\n   1.049 49.081\n   1.059 44.558\n   1.077 35.963\n   1.1 26.689\n   1.167 9.273\n   1.2 0.0\n",
    "source": {
      "file": "Quest_F41W.eng",
      "motorId": "629ee8bae0d045000403682e",
      "simfileId": "62a01e29e0d0450004036ef0",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/62a01e29e0d0450004036ef0/",
      "designation": "F41W",
      "manufacturer": "Quest Aerospace",
      "commonName": "F41"
    }
  }
];
