// GENERATED by scripts/gen-motors.mjs — do not edit by hand.
//
// The bundled offline motor database: authentic RASP thrust curves from ThrustCurve.org,
// inlined verbatim so the simulator resolves motors client-side with no network. Thrust-vs-
// time is factual certification / test-stand data; each entry records its ThrustCurve.org
// simfile id, info URL, and license for auditability. Regenerate with:
//   node scripts/gen-motors.mjs

export interface CatalogSource {
  file: string;
  motorId: string | null;
  simfileId: string | null;
  license: string | null;
  infoUrl: string | null;
}

export interface CatalogEntry {
  /** Raw RASP .eng text, parsed at load by lib/motors/eng.ts. */
  eng: string;
  source: CatalogSource;
}

export const MOTOR_CATALOG: CatalogEntry[] = [
  {
    "eng": ";Aerotech D21 RASP.ENG file made from NAR published data\n;File produced July 4, 2000\n;Submitted to ThrustCurve.org by Chris Kobel (3/29/07)\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD21T 18 70 4-7 0.0096 0.025 AT \n   0.01   1.367\n   0.021 19.367\n   0.029 32.12\n   0.037 31.667\n   0.051 30.528\n   0.094 30.074\n   0.115 31.213\n   0.133 30.074\n   0.177 30.76\n   0.189 29.842\n   0.203 30.528\n   0.226 29.842\n   0.275 28.935\n   0.296 29.389\n   0.331 28.027\n   0.421 25.971\n   0.478 24.146\n   0.579 20.728\n   0.659 17.774\n   0.739 14.356\n   0.799  9.569\n   0.852  4.557\n   0.899  1.139\n   0.94   0\n",
    "source": {
      "file": "AeroTech_D21T.eng",
      "motorId": "5f4294d20002310000000023",
      "simfileId": "5f4294d20002e9000000027d",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000027d/"
    }
  },
  {
    "eng": "; Aerotech E30 RASP.ENG file made from NAR published data\n; File produced Sept 30, 2010\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nE30 24 70 4-7 .0178 .047 A\n0.006 49.3000\n0.030 45.7010\n0.038 47.1810\n0.050 45.1800\n0.062 43.7010\n0.112 43.4020\n0.138 42.8170\n0.206 42.0730\n0.238 43.3680\n0.282 41.5750\n0.324 41.0860\n0.342 41.7330\n0.362 40.1680\n0.436 38.1580\n0.524 36.3980\n0.650 32.9720\n0.712 31.0500\n0.836 25.0770\n0.874 22.4750\n0.888 21.5080\n0.900 20.0080\n0.912 17.1760\n0.924 13.3000\n0.942 6.6500\n0.962 2.7550\n0.974 1.6370\n0.988 0.7810\n1.000 0.4290\n1.010 0.1410\n1.020 0.0000\n",
    "source": {
      "file": "AeroTech_E30T.eng",
      "motorId": "5f4294d20002310000000034",
      "simfileId": "62431a34ee302a00044520da",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/62431a34ee302a00044520da/"
    }
  },
  {
    "eng": ";\n;Aerotech F50 RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case F50T motors.\nF50T 29 98 4-6-9 0.0336 0.0898 AeroTech\n0.013 73.762\n0.0326 70.383\n0.267 69.82\n0.518 67.005\n0.792 56.87\n0.906 50.676\n1 44.482\n1.036 39.978\n1.107 23.649\n1.199 6.194\n1.316 1.126\n1.43 0\n",
    "source": {
      "file": "AeroTech_F50T.eng",
      "motorId": "5f4294d20002310000000049",
      "simfileId": "5f4294d20002e9000000045b",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000045b/"
    }
  },
  {
    "eng": "F67W 29 83 4-6-9 0.03 0.08 AT\n   0.002 66.662\n   0.008 71.441\n   0.016 74.505\n   0.039 77.936\n   0.068 80.632\n   0.099 82.592\n   0.148 84.43\n   0.201 85.533\n   0.257 86.146\n   0.298 86.023\n   0.399 84.185\n   0.483 82.96\n   0.499 82.347\n   0.568 80.019\n   0.601 78.794\n   0.625 77.936\n   0.654 78.058\n   0.672 75.853\n   0.687 71.073\n   0.7 67.52\n   0.714 62.005\n   0.731 53.06\n   0.748 44.482\n   0.764 35.659\n   0.778 26.836\n   0.789 20.954\n   0.797 18.013\n   0.812 12.499\n   0.832 7.107\n   0.849 3.676\n   0.87 1.225\n   0.898 0.368\n   0.92 0.0\n",
    "source": {
      "file": "AeroTech_F67W.eng",
      "motorId": "5f4294d2000231000000045a",
      "simfileId": "5f4294d20002e9000000088a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000088a/"
    }
  },
  {
    "eng": ";\n;Aerotech G40W RASP.ENG file made by Tim Van Milligan\n;For RockSim www.RockSim.com\n;File Created March 2, 2005\n;Thrust curve supplied by Aerotech for the molded case G40W motors.\nG40W 29 124 4-7-10 0.0538 0.123 AeroTech\n0.024 74.325\n0.057 67.005\n0.252 65.879\n0.5 63.063\n0.765 60.248\n1 54.054\n1.25 47.298\n1.502 36.599\n1.751 25.338\n1.999 12.951\n2.121 3.941\n2.3 0\n",
    "source": {
      "file": "AeroTech_G40W.eng",
      "motorId": "5f4294d20002310000000059",
      "simfileId": "5f4294d20002e90000000463",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000463/"
    }
  },
  {
    "eng": ";G80 New Blue Thunder\nG80NBT 29 123.825 4-7-10 0.069 0.129 AT \n0.013 89.054\n0.018 101.584\n0.029 105.388\n0.047 102.927\n0.104 100.018\n0.19 102.255\n0.268 104.94\n0.306 104.269\n0.352 105.835\n0.41 104.94\n0.432 106.73\n0.512 105.612\n0.563 106.954\n0.591 104.493\n0.62 106.283\n0.715 103.15\n0.76 103.374\n0.806 101.36\n0.848 102.032\n1.2 88.383\n1.243 77.866\n1.269 57.952\n1.302 44.079\n1.329 34.011\n1.367 26.403\n1.398 22.823\n1.433 20.585\n1.48 21.704\n1.508 20.809\n1.584 13.201\n1.604 11.635\n1.652 11.188\n1.683 5.37\n1.701 0\n;\n",
    "source": {
      "file": "AeroTech_G80T.eng",
      "motorId": "5f4294d20002310000000068",
      "simfileId": "5f4294d20002e900000007dd",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007dd/"
    }
  },
  {
    "eng": "; AeroTech H128W\n; converted from TMT test stand data 1997 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH128W 29 194 14 0.09408 0.2016 AT\n   0.024 102.423\n   0.074 175.203\n   0.125 181.379\n   0.176 179.281\n   0.226 181.423\n   0.277 186.074\n   0.328 190.483\n   0.378 189.509\n   0.429 186.162\n   0.480 184.114\n   0.530 180.300\n   0.581 174.144\n   0.632 172.019\n   0.683 169.360\n   0.734 166.017\n   0.784 161.882\n   0.835 157.331\n   0.886 153.073\n   0.936 151.985\n   0.988 139.902\n   1.039 87.865\n   1.089 40.857\n   1.140 14.328\n   1.191 4.330\n   1.242 1.550\n   1.293 0.000\n",
    "source": {
      "file": "AeroTech_H128W.eng",
      "motorId": "5f4294d20002310000000083",
      "simfileId": "5f4294d20002e9000000000d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000d/"
    }
  },
  {
    "eng": "; AeroTech H148R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nH148R 38 152 0 0.14784 0.30912 AT\n   0.027 77.232\n   0.088 174.296\n   0.148 185.046\n   0.208 190.458\n   0.268 192.497\n   0.327 191.996\n   0.388 188.790\n   0.448 187.548\n   0.509 182.697\n   0.570 178.151\n   0.630 172.906\n   0.690 169.607\n   0.750 164.510\n   0.810 158.375\n   0.870 153.019\n   0.930 146.810\n   0.991 139.443\n   1.053 132.001\n   1.112 123.271\n   1.173 112.559\n   1.233 104.737\n   1.292 97.657\n   1.353 94.932\n   1.413 60.644\n   1.474 13.007\n   1.535 0.000\n",
    "source": {
      "file": "AeroTech_H148R.eng",
      "motorId": "5f4294d20002310000000087",
      "simfileId": "5f4294d20002e9000000000f",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000000f/"
    }
  },
  {
    "eng": ";\n; 38-240\n;  Greg Gardner - 09/15/06\nH669N  38 152  0  0.096  0.252  AT\n0.003  141\n0.006  523\n0.009  934\n0.012  1178\n0.016  926\n0.019  684\n0.022  487\n0.025  415\n0.028  622\n0.031  801\n0.0325  906\n0.034  866\n0.037  755\n0.04   737\n0.043  666\n0.047  737\n0.0485  802\n0.05   755\n0.053  791\n0.056  765\n0.059  755\n0.062  747\n0.069  737\n0.075  761\n0.082  755\n0.088  729\n0.093  741\n0.1    751\n0.2    703\n0.25   640\n0.3    586\n0.306  584\n0.309  576\n0.312  506\n0.318  292\n0.325  93\n0.329  0\n;\n",
    "source": {
      "file": "AeroTech_H669N.eng",
      "motorId": "5f4294d2000231000000009b",
      "simfileId": "5f4294d20002e9000000026a",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000026a/"
    }
  },
  {
    "eng": "; Aerotech I115W from TRA Cert Data\nI115W 54 156 6-10-14-P 0.229 0.58 AT\n   0.034 12.095\n   0.177 105.225\n   0.206 113.087\n   1.017 163.281\n   1.166 161.466\n   1.257 162.676\n   1.343 166.909\n   1.417 160.862\n   1.514 162.676\n   1.617 163.885\n   1.686 160.257\n   1.977 142.719\n   2.497 106.435\n   2.68 91.316\n   2.994 72.569\n   3.103 67.126\n   3.189 65.917\n   3.24 59.265\n   3.291 42.937\n   3.331 30.237\n   3.377 20.561\n   3.429 12.7\n   3.491 7.257\n   3.514 0.0\n",
    "source": {
      "file": "AeroTech_I115W.eng",
      "motorId": "5f4294d200023100000001e7",
      "simfileId": "5f4294d20002e90000000423",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000423/"
    }
  },
  {
    "eng": "; AeroTech I161W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI161W 38 191 0 0.189952 0.370048 AT\n   0.043 178.900\n   0.131 206.770\n   0.221 206.101\n   0.310 205.175\n   0.400 206.924\n   0.490 210.603\n   0.579 210.475\n   0.669 211.555\n   0.758 212.379\n   0.848 212.096\n   0.938 209.060\n   1.027 202.345\n   1.116 192.439\n   1.204 179.499\n   1.294 162.159\n   1.383 148.446\n   1.473 135.222\n   1.563 120.095\n   1.652 104.041\n   1.742 87.962\n   1.831 74.789\n   1.921 54.362\n   2.010 23.386\n   2.100 7.332\n   2.190 5.171\n   2.279 0.000\n",
    "source": {
      "file": "AeroTech_I161W.eng",
      "motorId": "5f4294d200023100000000b1",
      "simfileId": "5f4294d20002e9000000002d",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000002d/"
    }
  },
  {
    "eng": "; AeroTech I211W\n; converted from TMT test stand data 1999 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nI211W 38 240 0 0.247296 0.466368 AT\n   0.044 257.326\n   0.134 295.533\n   0.226 296.087\n   0.318 298.204\n   0.408 295.082\n   0.499 287.669\n   0.591 282.578\n   0.682 272.875\n   0.773 266.997\n   0.864 257.602\n   0.955 250.495\n   1.047 238.574\n   1.138 228.571\n   1.228 215.135\n   1.320 198.047\n   1.411 180.631\n   1.502 161.261\n   1.593 146.708\n   1.684 134.484\n   1.776 101.241\n   1.867 52.688\n   1.957 35.461\n   2.049 24.321\n   2.141 11.165\n   2.232 4.587\n   2.324 0.000\n",
    "source": {
      "file": "AeroTech_I211W.eng",
      "motorId": "5f4294d200023100000000b9",
      "simfileId": "5f4294d20002e90000000035",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000035/"
    }
  },
  {
    "eng": "; AeroTech J420R\n; provided by ThrustCurve.org (www.thrustcurve.org)\nJ420R 38 337 0 0.37632 0.6496 AT\n   0.031 61.083\n   0.095 563.470\n   0.160 525.283\n   0.224 521.242\n   0.288 527.371\n   0.352 537.088\n   0.418 535.138\n   0.481 534.623\n   0.545 530.245\n   0.610 526.447\n   0.674 517.203\n   0.738 510.279\n   0.802 500.887\n   0.868 479.450\n   0.931 460.675\n   0.995 438.594\n   1.060 409.647\n   1.124 383.454\n   1.188 361.024\n   1.252 339.741\n   1.318 319.194\n   1.381 296.714\n   1.445 195.191\n   1.510 61.984\n   1.575 7.220\n   1.640 0.000\n",
    "source": {
      "file": "AeroTech_J420R.eng",
      "motorId": "5f4294d2000231000000011c",
      "simfileId": "5f4294d20002e90000000057",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000057/"
    }
  },
  {
    "eng": "; AeroTech K550W\n; converted from TMT test stand data 1998 (www.tripoli.org)\n; provided by ThrustCurve.org (www.thrustcurve.org)\nK550W 54 410 0 0.919744 1.48736 AT\n   0.065 604.264\n   0.196 642.625\n   0.327 682.197\n   0.458 732.995\n   0.591 758.236\n   0.723 780.289\n   0.854 794.452\n   0.985 797.939\n   1.117 797.601\n   1.249 773.842\n   1.381 711.608\n   1.512 646.522\n   1.644 590.724\n   1.775 537.505\n   1.907 491.012\n   2.040 445.836\n   2.171 401.461\n   2.302 364.291\n   2.433 319.614\n   2.566 255.577\n   2.698 172.573\n   2.829 103.501\n   2.960 51.795\n   3.092 26.814\n   3.224 15.203\n   3.356 0.000\n",
    "source": {
      "file": "AeroTech_K550W.eng",
      "motorId": "5f4294d20002310000000146",
      "simfileId": "5f4294d20002e90000000071",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000071/"
    }
  },
  {
    "eng": ";\n;\nK660  54.0 572.00 7-17 1.17700 1.94900 CTI\n   0.07    1078.90 \n   0.23    1006.47 \n   0.40     966.76 \n   0.80     897.52 \n   1.20     842.72 \n   1.60     794.15 \n   2.01     744.52 \n   2.40     692.27 \n   2.54     671.37 \n   2.68     439.08 \n   2.80     400.68 \n   3.01     386.90 \n   3.20     234.31 \n   3.45     106.65 \n   3.60      44.03 \n   3.69       0.00\n",
    "source": {
      "file": "Cesaroni_2437K660-17A.eng",
      "motorId": "5f4294d20002310000000154",
      "simfileId": "5f4294d20002e90000000143",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000143/"
    }
  },
  {
    "eng": "; CTI Pro54-2G 838 J293BS 13A\nJ293BS 54 237 13-12-11-10-9-8-7-6-5-4-3 0.41600000000000004 0.84 CTI\n   0.019 22.847\n   0.032 250.277\n   0.044 386.32\n   0.06 302.202\n   0.073 256.508\n   0.13 285.586\n   0.266 309.471\n   0.487 318.818\n   0.734 325.049\n   1.432 324.01\n   1.786 309.471\n   2.074 294.933\n   2.33 280.394\n   2.488 273.124\n   2.58 272.086\n   2.634 258.585\n   2.713 163.044\n   2.795 70.618\n   2.852 20.77\n   2.896 0.0\n",
    "source": {
      "file": "Cesaroni_838J293-13A.eng",
      "motorId": "5f4294d200023100000002d8",
      "simfileId": "5f4294d20002e90000000674",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000674/"
    }
  },
  {
    "eng": ";Estes A10T RASP.ENG file made from NAR published data\n; File produced March 3, 2011\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nA10T 13 45 0 .0038 .00525 E\n0.016 0.492\n0.040 0.752\n0.062 0.962\n0.078 2.051\n0.096 2.858\n0.122 4.611\n0.138 6.054\n0.162 8.100\n0.180 9.502\n0.198 9.740\n0.212 8.204\n0.224 4.530\n0.238 2.054\n0.268 1.414\n0.292 1.385\n0.324 1.067\n0.364 1.099\n0.396 0.957\n0.446 0.995\n0.490 0.901\n0.574 0.909\n0.676 0.909\n0.782 1.031\n0.886 1.048\n0.980 1.029\n1.006 0.995\n1.038 1.049\n1.050 0.741\n1.060 0.000\n",
    "source": {
      "file": "Estes_A10.eng",
      "motorId": "5f4294d2000231000000000c",
      "simfileId": "624aff26a49a690004b83002",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/624aff26a49a690004b83002/"
    }
  },
  {
    "eng": "; Estes A8 RASP.ENG file made from NAR published data\n; File produced March 3, 2011\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\n A8 18 70 0 .00384 .01389 E\n0.016 1.080\n0.036 0.293\n0.050 0.259\n0.060 0.357\n0.070 0.419\n0.080 0.355\n0.102 0.781\n0.124 1.443\n0.152 2.966\n0.170 4.426\n0.202 7.160\n0.224 9.051\n0.246 9.555\n0.256 9.317\n0.276 7.958\n0.294 6.108\n0.326 4.235\n0.350 3.813\n0.376 3.997\n0.410 3.926\n0.452 3.724\n0.474 4.046\n0.502 4.092\n0.532 4.146\n0.534 0.000\n",
    "source": {
      "file": "Estes_A8.eng",
      "motorId": "5f4294d2000231000000000b",
      "simfileId": "5f4294d20002e90000000897",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000897/"
    }
  },
  {
    "eng": "; B4-4\nB4-4 18 70 P 0.006 0.0195 E\n   0.058 2.361\n   0.102 2.921\n   0.122 3.797\n   0.15 5.866\n   0.18 8.373\n   0.199 9.882\n   0.208 10.88\n   0.216 11.367\n   0.238 11.245\n   0.245 10.832\n   0.262 8.982\n   0.293 6.134\n   0.322 5.306\n   0.357 4.917\n   0.388 4.795\n   0.416 4.746\n   0.46 4.625\n   0.502 4.576\n   0.544 4.357\n   0.575 4.503\n   0.605 4.527\n   0.674 4.552\n   0.731 4.454\n   0.88 4.454\n   0.915 4.503\n   0.96 4.406\n   1.0 4.065\n   1.047 2.556\n   1.049 0.0\n",
    "source": {
      "file": "Estes_B4.eng",
      "motorId": "5f4294d2000231000000000e",
      "simfileId": "5f4294d20002e90000000834",
      "license": "PD",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000834/"
    }
  },
  {
    "eng": "; Estes B6-0 from NAR data by Mark Koelsch\nB6-0 18 70 0 0.0056 0.0156 E\n   0.036 1.364\n   0.064 2.727\n   0.082 4.215\n   0.111 6.694\n   0.135 9.05\n   0.146 9.545\n   0.172 11.901\n   0.181 12.149\n   0.191 11.901\n   0.211 9.174\n   0.239 7.314\n   0.264 6.074\n   0.275 5.95\n   0.333 5.207\n   0.394 4.835\n   0.445 4.835\n   0.556 4.339\n   0.667 4.587\n   0.723 4.339\n   0.78 4.339\n   0.793 4.091\n   0.812 2.603\n   0.833 1.24\n   0.857 0.0\n",
    "source": {
      "file": "Estes_B6.eng",
      "motorId": "5f4294d20002310000000010",
      "simfileId": "5f4294d20002e90000000414",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000414/"
    }
  },
  {
    "eng": ";\n;ESTES C11 RASP.ENG file made from NAR published data\n;File produced JANUARY 1, 2002\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nC11 24 70 0-3-5-7 0.012 0.0353 Estes \n0.034 1.692\n0.066 3.782\n0.107 7.566\n0.145 10.946\n0.183 14.832\n0.214 17.618\n0.226 18.213\n0.256 20.107\n0.281 21.208\n0.298 21.73\n0.306 20.206\n0.323 17.321\n0.337 14.931\n0.358 13.236\n0.385 11.947\n0.413 11.65\n0.468 10.946\n0.539 10.45\n0.619 10.648\n0.683 10.648\n0.715 10.648\n0.726 10.053\n0.74 8.163\n0.758 5.773\n0.778 3.185\n0.795 1.394\n0.81 0\n",
    "source": {
      "file": "Estes_C11.eng",
      "motorId": "5f4294d2000231000000001a",
      "simfileId": "5f4294d20002e900000004e8",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004e8/"
    }
  },
  {
    "eng": "; Estes C6 RASP.ENG file made from NAR published data\n; File produced October 3, 2000\n; The total impulse, peak thrust, average thrust and burn time are\n; the same as the averaged static test data on the NAR web site in\n; the certification file. The curve drawn with these data points is as\n; close to the certification curve as can be with such a limited\n; number of points (32) allowed with wRASP up to v1.6.\nC6 18 70 0-3-5-7 .0108 .0231 E\n0.031 0.946\n0.092 4.826\n0.139 9.936\n0.192 14.090\n0.209 11.446\n0.231 7.381\n0.248 6.151\n0.292 5.489\n0.370 4.921\n0.475 4.448\n0.671 4.258\n0.702 4.542\n0.723 4.164\n0.850 4.448\n1.063 4.353\n1.211 4.353\n1.242 4.069\n1.303 4.258\n1.468 4.353\n1.656 4.448\n1.821 4.448\n1.834 2.933\n1.847 1.325\n1.860 0.000\n",
    "source": {
      "file": "Estes_C6.eng",
      "motorId": "5f4294d20002310000000015",
      "simfileId": "69eb2379c7d63000021d8c29",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/69eb2379c7d63000021d8c29/"
    }
  },
  {
    "eng": ";\n;Estes D12 RASP.ENG file made from NAR published data\n;File produced October 3, 2000\n;The total impulse, peak thrust, average thrust and burn time are\n;the same as the averaged static test data on the NAR web site in\n;the certification file. The curve drawn with these data points is as\n;close to the certification curve as can be with such a limited\n;number of points (32) allowed with wRASP up to v1.6.\nD12 24 70 0-3-5-7 0.0211 0.0426 Estes \n0.049 2.569\n0.116 9.369\n0.184 17.275\n0.237 24.258\n0.282 29.73\n0.297 27.01\n0.311 22.589\n0.322 17.99\n0.348 14.126\n0.386 12.099\n0.442 10.808\n0.546 9.876\n0.718 9.306\n0.879 9.105\n1.066 8.901\n1.257 8.698\n1.436 8.31\n1.59 8.294\n1.612 4.613\n1.65 0\n",
    "source": {
      "file": "Estes_D12.eng",
      "motorId": "5f4294d20002310000000020",
      "simfileId": "5f4294d20002e900000004ea",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000004ea/"
    }
  },
  {
    "eng": "; Based on NAR Published Data, 7/31/12, C. J. Kobel\nE12 24 95 0-4-6-8 0.0359 0.0599 Estes\n   0.052 5.045\n   0.096 9.910\n   0.196 24.144\n   0.251 31.351\n   0.287 32.973\n   0.300 29.910\n   0.344 17.117\n   0.370 14.414\n   0.400 12.973\n   0.500 11.712\n   0.600 11.171\n   0.700 10.631\n   0.800 10.09\n   0.900 9.73\n   1.000 9.55\n   1.101 9.91\n   1.200 9.55\n   1.300 9.73\n   1.400 9.73\n   1.500 9.73\n   1.600 9.73\n   1.700 9.55\n   1.800 9.73\n   1.900 9.73\n   2.000 9.55\n   2.100 9.55\n   2.200 9.73\n   2.300 9.19\n   2.375 9.37\n   2.400 5.95\n   2.440 0.0\n",
    "source": {
      "file": "Estes_E12.eng",
      "motorId": "5f4294d200023100000003e3",
      "simfileId": "5f4294d20002e900000007ad",
      "license": "?",
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e900000007ad/"
    }
  },
  {
    "eng": "; Estes E9-0 by Mark Koelsch from NAR data\nE9-0 24 95 0 0.0358 0.056799999999999996 E\n   0.046 1.913\n   0.235 16.696\n   0.273 18.435\n   0.326 14.957\n   0.38 12.174\n   0.44 10.435\n   0.835 9.043\n   1.093 8.87\n   1.496 8.696\n   1.997 8.696\n   2.498 8.696\n   3.014 9.217\n   3.037 5.043\n   3.067 1.217\n   3.09 0.0\n",
    "source": {
      "file": "Estes_E9.eng",
      "motorId": "5f4294d20002310000000028",
      "simfileId": "5f4294d20002e90000000416",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e90000000416/"
    }
  },
  {
    "eng": "; Quest C6-0 from NAR data\nC6-0 18 70 0 0.0083 0.0216 Q\n   0.02 0.497\n   0.057 2.539\n   0.089 5.132\n   0.129 7.947\n   0.159 9.437\n   0.171 21.247\n   0.181 23.234\n   0.194 22.958\n   0.204 22.185\n   0.218 19.592\n   0.233 17.881\n   0.258 10.486\n   0.308 2.428\n   0.338 2.539\n   0.385 2.98\n   0.412 3.091\n   0.442 3.422\n   0.459 2.98\n   0.536 3.256\n   0.732 3.311\n   0.747 2.483\n   0.78 2.98\n   1.323 3.587\n   1.365 2.815\n   1.887 3.808\n   1.974 3.256\n   2.1 3.532\n   2.227 3.201\n   2.247 0.0\n",
    "source": {
      "file": "Quest_C6.eng",
      "motorId": "5f4294d20002310000000016",
      "simfileId": "5f4294d20002e9000000041c",
      "license": null,
      "infoUrl": "https://www.thrustcurve.org/simfiles/5f4294d20002e9000000041c/"
    }
  }
];
