// Regenerate the bundled motor catalog (lib/motors/catalog.ts) from the raw RASP `.eng`
// files under lib/motors/curves/ and their provenance record (curves/provenance.json).
//
// The `.eng` files are authentic, published motor thrust curves downloaded from
// ThrustCurve.org (thrust-vs-time is factual test-stand / certification data). This script
// inlines them into a TypeScript module so the database ships in the bundle and works
// fully offline — no filesystem or network at runtime. It is a DEV tool: it is not part of
// the build (`prebuild` is gen-og only) and needs no network. Re-run it after adding a
// `.eng` file:  node scripts/gen-motors.mjs
//
// Every entry keeps its ThrustCurve.org simfile id, info URL, and license so the source of
// each curve is auditable from the committed code.
import { readFile, writeFile, readdir } from "node:fs/promises";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const curvesDir = resolve(here, "..", "lib", "motors", "curves");
const outFile = resolve(here, "..", "lib", "motors", "catalog.ts");

const prov = JSON.parse(await readFile(resolve(curvesDir, "provenance.json"), "utf-8"));
const byFile = new Map(prov.map((p) => [p.file, p]));

const files = (await readdir(curvesDir)).filter((f) => f.endsWith(".eng")).sort();

const entries = [];
for (const file of files) {
  const eng = await readFile(resolve(curvesDir, file), "utf-8");
  const p = byFile.get(file) ?? {};
  entries.push({
    eng,
    source: {
      file: basename(file),
      motorId: p.motorId ?? null,
      simfileId: p.simfileId ?? null,
      license: p.license ?? null,
      infoUrl: p.simfileId ? `https://www.thrustcurve.org/simfiles/${p.simfileId}/` : null,
    },
  });
}

const header = `// GENERATED by scripts/gen-motors.mjs — do not edit by hand.
//
// The bundled offline motor database: authentic RASP thrust curves from ThrustCurve.org,
// inlined verbatim so the simulator resolves motors client-side with no network. Thrust-vs-
// time is factual certification / test-stand data; each entry records its ThrustCurve.org
// simfile id, info URL, and license for auditability. Regenerate with:
//   node scripts/gen-motors.mjs

export interface CatalogSource {
  file: string;
  motorId: string | null;
  simfileId: string | null;
  license: string | null;
  infoUrl: string | null;
}

export interface CatalogEntry {
  /** Raw RASP .eng text, parsed at load by lib/motors/eng.ts. */
  eng: string;
  source: CatalogSource;
}

export const MOTOR_CATALOG: CatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

await writeFile(outFile, header);
console.log(`gen-motors: wrote ${entries.length} motors to lib/motors/catalog.ts`);
