// Regenerate the bundled motor catalog (lib/motors/catalog.ts) from the raw RASP `.eng`
// files under lib/motors/curves/ and their provenance record (curves/provenance.json).
//
// The `.eng` files are authentic, published motor thrust curves downloaded from
// ThrustCurve.org (thrust-vs-time is factual test-stand / certification data). This script
// inlines them into a TypeScript module so the database ships in the bundle and works
// fully offline — no filesystem or network at runtime. It is a DEV tool: it is not part of
// the build (`prebuild` is gen-og only) and needs no network. Re-run it after adding a
// `.eng` file:  node scripts/gen-motors.mjs
//
// Every entry keeps its ThrustCurve.org simfile id, info URL, and license so the source of
// each curve is auditable from the committed code.
import { readFile, writeFile, readdir } from "node:fs/promises";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const curvesDir = resolve(here, "..", "lib", "motors", "curves");
const outFile = resolve(here, "..", "lib", "motors", "catalog.ts");

const prov = JSON.parse(await readFile(resolve(curvesDir, "provenance.json"), "utf-8"));
const byFile = new Map(prov.map((p) => [p.file, p]));

const files = (await readdir(curvesDir)).filter((f) => f.endsWith(".eng")).sort();

const entries = [];
for (const file of files) {
  const eng = await readFile(resolve(curvesDir, file), "utf-8");
  const p = byFile.get(file) ?? {};
  entries.push({
    eng,
    source: {
      file: basename(file),
      motorId: p.motorId ?? null,
      simfileId: p.simfileId ?? null,
      license: p.license ?? null,
      infoUrl: p.simfileId ? `https://www.thrustcurve.org/simfiles/${p.simfileId}/` : null,
      // ThrustCurve.org's own designation and manufacturer for this motor. A RASP header
      // carries whatever the curve's author typed — an abbreviated designation ("E30" for an
      // E30T, "G80NBT" for a G80T) and a one-or-two-letter maker code ("A", "AT", "E") — so
      // the catalogued identity comes from the certification record instead, and the header
      // is only the fallback. Matching a design's motor reference against the abbreviation is
      // what left real files with no propulsion at all.
      designation: p.designation ?? null,
      manufacturer: p.manufacturer ?? null,
      // ThrustCurve's *common* name — the class-and-thrust name a motor is sold and talked
      // about by ("J285"), as distinct from the manufacturer part number ("648J285-15A").
      // Design files use one or the other, so both are matchable identities.
      commonName: p.commonName ?? null,
    },
  });
}

const header = `// GENERATED by scripts/gen-motors.mjs — do not edit by hand.
//
// The bundled offline motor database: authentic RASP thrust curves from ThrustCurve.org,
// inlined verbatim so the simulator resolves motors client-side with no network. Thrust-vs-
// time is factual certification / test-stand data; each entry records its ThrustCurve.org
// simfile id, info URL, and license for auditability. Regenerate with:
//   node scripts/gen-motors.mjs

export interface CatalogSource {
  file: string;
  motorId: string | null;
  simfileId: string | null;
  license: string | null;
  infoUrl: string | null;
  /** ThrustCurve.org's designation for this motor, when recorded — the catalogued identity
   *  matching runs against, in preference to the RASP header's abbreviation. */
  designation: string | null;
  /** ThrustCurve.org's manufacturer, likewise, in preference to the header's maker code. */
  manufacturer: string | null;
  /** ThrustCurve.org's common (class-and-thrust) name, e.g. "J285" for part number
   *  "648J285-15A" — the other published name a design file may reference. */
  commonName: string | null;
}

export interface CatalogEntry {
  /** Raw RASP .eng text, parsed at load by lib/motors/eng.ts. */
  eng: string;
  source: CatalogSource;
}

export const MOTOR_CATALOG: CatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

await writeFile(outFile, header);
console.log(`gen-motors: wrote ${entries.length} motors to lib/motors/catalog.ts`);
